import FamilyChecks
import Checks
#print axioms DeltaReduce.ShardFamily.Layout
#print axioms DeltaReduce.ShardFamily.Selector
#print axioms DeltaReduce.ShardFamily.base
#print axioms DeltaReduce.ShardFamily.select
#print axioms DeltaReduce.ShardFamily.select_self
#print axioms DeltaReduce.ShardFamily.Whole
#print axioms DeltaReduce.ShardFamily.Family
#print axioms DeltaReduce.ShardFamily.project
#print axioms DeltaReduce.ShardFamily.reconstruct
#print axioms DeltaReduce.ShardFamily.reconstruct_values
#print axioms DeltaReduce.ShardFamily.reconstruct_project
#print axioms DeltaReduce.ShardFamily.project_reconstruct
#print axioms DeltaReduce.ShardFamily.injective
#print axioms DeltaReduce.ShardFamily.rows
#print axioms DeltaReduce.ShardFamily.complete_rows
#print axioms DeltaReduce.ShardFamily.exact_rows
#print axioms DeltaReduce.ShardFamily.validateRows
#print axioms DeltaReduce.ShardFamily.validate_exact
#print axioms DeltaReduce.ShardFamily.scalarView
#print axioms DeltaReduce.ShardFamily.one_common
#print axioms DeltaReduce.ShardFamily.common_predicate
#print axioms DeltaReduce.ShardFamily.signer_union
#print axioms DeltaReduce.ShardFamily.all_views_iff
#print axioms DeltaReduce.ShardFamily.ordered
#print axioms DeltaReduce.ShardFamily.flatten
#print axioms DeltaReduce.ShardFamily.original_shard_count
#print axioms DeltaReduce.ShardFamily.complete_ordered_reconstruction
#print axioms DeltaReduce.ManifestFamily.corpusShapes
#print axioms DeltaReduce.ManifestFamily.positiveAndBounded
#print axioms DeltaReduce.ManifestFamily.layout
#print axioms DeltaReduce.ManifestFamily.whole
#print axioms DeltaReduce.ManifestFamily.family
#print axioms DeltaReduce.ManifestFamily.full_reconstruction
#print axioms DeltaReduce.ManifestFamily.bounded_layout
#print axioms DeltaReduce.ManifestFamily.ordered_source
#print axioms DeltaReduce.ManifestFamily.raw_identity
#print axioms DeltaReduce.ManifestFamily.coordinate_source
#print axioms DeltaReduce.ManifestFamily.original
#print axioms DeltaReduce.ManifestFamily.originalWidths
#print axioms DeltaReduce.ManifestFamily.originalCount
#print axioms DeltaReduce.ManifestFamily.originalStarts
#print axioms DeltaReduce.ManifestFamily.originalRoundtrip
#print axioms DeltaReduce.ManifestFamily.originalFullValues
#print axioms DeltaReduce.ManifestFamily.originalNoNewObjects
#print axioms DeltaReduce.NativeFamily.single
#print axioms DeltaReduce.NativeFamily.parameterLayout
#print axioms DeltaReduce.NativeFamily.parameterSlot
#print axioms DeltaReduce.NativeFamily.parameterWhole
#print axioms DeltaReduce.NativeFamily.parameterFamily
#print axioms DeltaReduce.NativeFamily.parameterRoundtrip
#print axioms DeltaReduce.NativeFamily.parameterCoordinate
#print axioms DeltaReduce.NativeFamily.parameterOriginalRows
#print axioms DeltaReduce.NativeFamily.reconstructedBody
#print axioms DeltaReduce.NativeFamily.completeBodyRecovered
#print axioms DeltaReduce.NativeFamily.originalBodyBytes
#print axioms DeltaReduce.NativeFamily.oldScalarResult
#print axioms DeltaReduce.NativeFamily.parameterFromVote
#print axioms DeltaReduce.NativeFamily.parameterFromVoteEncoded
#print axioms DeltaReduce.NativeFamily.preparedFamily
#print axioms DeltaReduce.NativeFamily.preparedRecordIdentity
#print axioms DeltaReduce.NativeFamily.preparedWholeBodyRecovered
#print axioms DeltaReduce.NativeFamily.preparedOriginalCommand
#print axioms DeltaReduce.NativeFamily.ApplyCell
#print axioms DeltaReduce.NativeFamily.applyCell
#print axioms DeltaReduce.NativeFamily.applyLayout
#print axioms DeltaReduce.NativeFamily.applySlot
#print axioms DeltaReduce.NativeFamily.applyWhole
#print axioms DeltaReduce.NativeFamily.applyFamily
#print axioms DeltaReduce.NativeFamily.applyModelReconstructed
#print axioms DeltaReduce.NativeFamily.applyOriginalHashPreimages
#print axioms DeltaReduce.NativeFamily.applyArithmeticCoordinate
#print axioms DeltaReduce.NativeFamily.certificateSignersUnchanged
#print axioms DeltaReduce.NativeFamily.originalRecordUnchanged
#print axioms DeltaReduce.StateFamily.Layout
#print axioms DeltaReduce.StateFamily.ofValidated
#print axioms DeltaReduce.StateFamily.shards
#print axioms DeltaReduce.StateFamily.globalIndex
#print axioms DeltaReduce.StateFamily.whole
#print axioms DeltaReduce.StateFamily.family
#print axioms DeltaReduce.StateFamily.globalCovered
#print axioms DeltaReduce.StateFamily.contains
#print axioms DeltaReduce.StateFamily.read
#print axioms DeltaReduce.StateFamily.readOriginal
#print axioms DeltaReduce.StateFamily.rebuild
#print axioms DeltaReduce.StateFamily.collectExact
#print axioms DeltaReduce.StateFamily.fullOrderedState
#print axioms DeltaReduce.StateFamily.globalInjective
#print axioms DeltaReduce.StateFamily.exactlyOnce
#print axioms DeltaReduce.StateFamily.nativeLayout
#print axioms DeltaReduce.StateFamily.nativeModelShape
#print axioms DeltaReduce.StateFamily.nativeCell
#print axioms DeltaReduce.StateFamily.nativeValues
#print axioms DeltaReduce.StateFamily.nativeFamily
#print axioms DeltaReduce.StateFamily.nativeCompleteState
#print axioms DeltaReduce.StateFamily.nativeOriginalLayout
#print axioms DeltaReduce.StateFamily.nativeNextVectors
#print axioms DeltaReduce.StateFamily.nativeRebuildHashPreimages
#print axioms DeltaReduce.FamilyTransferChecks.layout
#print axioms DeltaReduce.FamilyTransferChecks.first
#print axioms DeltaReduce.FamilyTransferChecks.last
#print axioms DeltaReduce.FamilyTransferChecks.firstCoordinates
#print axioms DeltaReduce.FamilyTransferChecks.lastCoordinates
#print axioms DeltaReduce.FamilyTransferChecks.original36
#print axioms DeltaReduce.FamilyTransferChecks.firstShard
#print axioms DeltaReduce.FamilyTransferChecks.originalRows
#print axioms DeltaReduce.FamilyTransferChecks.missingRejects
#print axioms DeltaReduce.FamilyTransferChecks.duplicateRejects
#print axioms DeltaReduce.FamilyTransferChecks.swappedRejects
#print axioms DeltaReduce.FamilyTransferChecks.valueRejects
#print axioms DeltaReduce.FamilyTransferChecks.noHiddenCrossShardDependency
#print axioms DeltaReduce.FamilyInputs.Choice
#print axioms DeltaReduce.FamilyInputs.collectExists
#print axioms DeltaReduce.FamilyInputs.Block
#print axioms DeltaReduce.FamilyInputs.loadBlock
#print axioms DeltaReduce.FamilyInputs.Entry
#print axioms DeltaReduce.FamilyInputs.Entries
#print axioms DeltaReduce.FamilyInputs.loadEntries
#print axioms DeltaReduce.FamilyInputs.entryAssignments
#print axioms DeltaReduce.FamilyInputs.Corpus
#print axioms DeltaReduce.FamilyInputs.loadCorpus
#print axioms DeltaReduce.FamilyInputs.cellsAt
#print axioms DeltaReduce.FamilyInputs.cellSource
#print axioms DeltaReduce.FamilyInputs.cellsComplete
#print axioms DeltaReduce.FamilyInputs.cellsContributions
#print axioms DeltaReduce.FamilyInputs.scalarRows
#print axioms DeltaReduce.FamilyInputs.selectedRowsExact
#print axioms DeltaReduce.FamilyInputs.entryInput
#print axioms DeltaReduce.FamilyInputs.entryInputComplete
#print axioms DeltaReduce.FamilyInputs.entryInputLocality
#print axioms DeltaReduce.FamilyInputs.entryInputSource
#print axioms DeltaReduce.FamilyInputs.selectedCellHasOriginalBytes
#print axioms DeltaReduce.FamilyInputs.selectedCellNumbers
#print axioms DeltaReduce.FamilyInputs.inputRetainsEligibleOrder
#print axioms DeltaReduce.FamilyInputs.selectedCurrent
#print axioms DeltaReduce.FamilyInputs.selectedCurrentIsFamily
#print axioms DeltaReduce.FamilyInputs.selectedCurrentCellSource
#print axioms DeltaReduce.FamilyInputs.Projected
#print axioms DeltaReduce.FamilyInputs.project
#print axioms DeltaReduce.FamilyInputs.image
#print axioms DeltaReduce.FamilyInputs.encode
#print axioms DeltaReduce.FamilyInputs.completePublicFields
#print axioms DeltaReduce.FamilyInputs.originalNamespaces
#print axioms DeltaReduce.FamilyInputs.projectedQSource
#print axioms DeltaReduce.FamilyInputs.projectedInputOrigin
#print axioms DeltaReduce.FamilyInputs.projectedTicketNames
#print axioms DeltaReduce.FamilyInputs.projectedTicketHasExactShape
#print axioms DeltaReduce.FamilyInputs.projectedTicketWeightValid
#print axioms DeltaReduce.FamilyInputs.projectedQuantumValid
#print axioms DeltaReduce.FamilyInputs.projectedCurrentRange
#print axioms DeltaReduce.FamilyInputs.collectedKeys
#print axioms DeltaReduce.FamilyInputs.projectedDomainNames
#print axioms DeltaReduce.FamilyInputs.projectedDomainShape
#print axioms DeltaReduce.FamilyInputs.projectedDomainPositive
#print axioms DeltaReduce.FamilyInputs.projectedTicketDenominator
#print axioms DeltaReduce.FamilyInputs.projectedTicketDomain
#print axioms DeltaReduce.FamilyInputs.projectedMixtureGuard
#print axioms DeltaReduce.FamilyInputs.projectedCurrentNames
#print axioms DeltaReduce.FamilyInputs.InputNumericGuards
#print axioms DeltaReduce.FamilyInputs.allInputNumericGuards
#print axioms DeltaReduce.FamilyInputs.onlyMember
#print axioms DeltaReduce.FamilyInputs.qAtAgreesWithCell
#print axioms DeltaReduce.FamilyInputs.collectedAtInput
#print axioms DeltaReduce.FamilyInputs.collectInputHasOutput
#print axioms DeltaReduce.FamilyInputs.derivedTicketFilterNames
#print axioms DeltaReduce.FamilyInputs.collectPaired
#print axioms DeltaReduce.FamilyInputs.readImageRow
#print axioms DeltaReduce.FamilyInputs.imageRows
#print axioms DeltaReduce.FamilyInputs.selectedInputIsExposed
#print axioms DeltaReduce.FamilyInputs.exposedTicketForCell
#print axioms DeltaReduce.FamilyInputs.exposedCellValue
#print axioms DeltaReduce.FamilyInputs.publicOrderIsNativeMemberOrder
#print axioms DeltaReduce.FamilyInputs.publicRowsAreSelectedNativeRows
#print axioms DeltaReduce.FamilyInputs.selectedCurrentNames
#print axioms DeltaReduce.FamilyInputs.selectedCurrentAt
#print axioms DeltaReduce.FamilyAuthority.configuredAlias
#print axioms DeltaReduce.FamilyAuthority.collectedValueSource
#print axioms DeltaReduce.FamilyAuthority.Projection
#print axioms DeltaReduce.FamilyAuthority.Projection.round
#print axioms DeltaReduce.FamilyAuthority.Projection.isc
#print axioms DeltaReduce.FamilyAuthority.Projection.seed
#print axioms DeltaReduce.FamilyAuthority.Projection.ec
#print axioms DeltaReduce.FamilyAuthority.Projection.apc
#print axioms DeltaReduce.FamilyAuthority.Projection.fields
#print axioms DeltaReduce.FamilyAuthority.Projection.value
#print axioms DeltaReduce.FamilyAuthority.project
#print axioms DeltaReduce.FamilyAuthority.Checked
#print axioms DeltaReduce.FamilyAuthority.check
#print axioms DeltaReduce.FamilyAuthority.checkedWholeAuthority
#print axioms DeltaReduce.FamilyAuthority.completeAuthorityInventory
#print axioms DeltaReduce.FamilyAuthority.authorityHasAllCheckedInputs
#print axioms DeltaReduce.FamilyAuthority.authorityHasOriginalParent
#print axioms DeltaReduce.FamilyAuthority.authorityHasBoundSchemaAndProfiles
#print axioms DeltaReduce.FamilyAuthority.coefficientUsesBothAPCAndPlan
#print axioms DeltaReduce.FamilyAuthority.seedAndNormUseNativeParents
#print axioms DeltaReduce.FamilyAuthority.exactConstructedParentChain
#print axioms DeltaReduce.FamilyAuthority.canonicalISCRootIsExactEntrySet
#print axioms DeltaReduce.FamilyAuthority.allNativeCommitmentsRetained
#print axioms DeltaReduce.FamilyAuthority.domainAliasComplete
#print axioms DeltaReduce.FamilyAuthority.shardAliasComplete
#print axioms DeltaReduce.FamilyAuthority.currentTableTotal
#print axioms DeltaReduce.FamilyAuthority.completeISCArtifactOrigin
#print axioms DeltaReduce.FamilyAuthority.nativeParentEdgesChecked
#print axioms DeltaReduce.FamilyAuthority.completeNativeParentPayloads
#print axioms DeltaReduce.FamilyAuthority.eligibleMemberSource
#print axioms DeltaReduce.FamilyAuthority.committedMemberSource
#print axioms DeltaReduce.FamilyAuthority.omittedMemberRequiresInputCompletion
#print axioms DeltaReduce.FamilyAuthority.eligibleSetsAreIdentical
#print axioms DeltaReduce.FamilyAuthority.currentTablesFromBoundVectors
#print axioms DeltaReduce.FamilyAuthority.structuredCurrentValuesShareSchema
#print axioms DeltaReduce.FamilyAuthority.authorityEntriesPreserveSource
#print axioms DeltaReduce.FamilyAuthority.canonicalLookup
#print axioms DeltaReduce.FamilyAuthority.canonicalField
#print axioms DeltaReduce.FamilyAuthority.recordKeys
#print axioms DeltaReduce.FamilyAuthority.canonicalRecord
#print axioms DeltaReduce.FamilyAuthority.encodedKey
#print axioms DeltaReduce.FamilyAuthority.insertKeysOrdered
#print axioms DeltaReduce.FamilyAuthority.sortedKeysOrdered
#print axioms DeltaReduce.FamilyAuthority.canonicalSet
#print axioms DeltaReduce.FamilyAuthority.pairKeys
#print axioms DeltaReduce.FamilyAuthority.pairCanonical
#print axioms DeltaReduce.FamilyAuthority.functionCanonicalParts
#print axioms DeltaReduce.FamilyAuthority.functionCanonicalFromParts
#print axioms DeltaReduce.FamilyAuthority.currentRowsKeys
#print axioms DeltaReduce.FamilyAuthority.currentTableCanonicalSameKeys
#print axioms DeltaReduce.FamilyAuthority.atomLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.headerLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.entryLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.entriesLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.projectFromComputed
#print axioms DeltaReduce.FamilyAuthority.constructedAuthorityCanonical
#print axioms DeltaReduce.FamilyAuthority.checkedAuthorityFromConstructed
#print axioms DeltaReduce.FamilyParameter.Projection
#print axioms DeltaReduce.FamilyParameter.project
#print axioms DeltaReduce.FamilyParameter.Projection.fields
#print axioms DeltaReduce.FamilyParameter.Projection.body
#print axioms DeltaReduce.FamilyParameter.Checked
#print axioms DeltaReduce.FamilyParameter.check
#print axioms DeltaReduce.FamilyParameter.computedWholeBody
#print axioms DeltaReduce.FamilyParameter.allFields
#print axioms DeltaReduce.FamilyParameter.entireAuthority
#print axioms DeltaReduce.FamilyParameter.entireParents
#print axioms DeltaReduce.FamilyParameter.sourceBeforeSelection
#print axioms DeltaReduce.FamilyParameter.exactNativeCoordinate
#print axioms DeltaReduce.FamilyParameter.publicCoordinateChecked
#print axioms DeltaReduce.FamilyParameter.samePublicInputsComputeBody
#print axioms DeltaReduce.FamilyParameter.actualInputImageComputesBody
#print axioms DeltaReduce.FamilyParameter.constructedBodyCanonical
#print axioms DeltaReduce.FamilyParameter.sourceAliases
#print axioms DeltaReduce.FamilyParameter.originalBodyUnchanged
#print axioms DeltaReduce.FamilyParameter.sameFrame
#print axioms DeltaReduce.FamilyParameter.originalNamespaces
#print axioms DeltaReduce.FamilyParameter.originalEntry
#print axioms DeltaReduce.FamilyParameter.parameterConstructorTotal
#print axioms DeltaReduce.FamilyParameter.parameterFromAuthority
#print axioms DeltaReduce.FamilyParameter.checkedParameterFromAuthority
#print axioms DeltaReduce.FamilyApplyArithmetic.conversion
#print axioms DeltaReduce.FamilyApplyArithmetic.conversionWidthsAgree
#print axioms DeltaReduce.FamilyApplyArithmetic.Converted
#print axioms DeltaReduce.FamilyApplyArithmetic.checkConversion
#print axioms DeltaReduce.FamilyApplyArithmetic.conversionChecksAllProducts
#print axioms DeltaReduce.FamilyApplyArithmetic.Conversions
#print axioms DeltaReduce.FamilyApplyArithmetic.checkConversions
#print axioms DeltaReduce.FamilyApplyArithmetic.everyConversionChecked
#print axioms DeltaReduce.FamilyApplyArithmetic.Checked
#print axioms DeltaReduce.FamilyApplyArithmetic.check
#print axioms DeltaReduce.FamilyApplyArithmetic.outputIdentity
#print axioms DeltaReduce.FamilyApplyArithmetic.originalRowsFromPlacedConvertedValues
#print axioms DeltaReduce.FamilyApplyArithmetic.noCertifiedConversionOmitted
#print axioms DeltaReduce.FamilyApplyArithmetic.originalOutputsMeetModelRange
#print axioms DeltaReduce.FamilyApply.Leaves
#print axioms DeltaReduce.FamilyApply.projectLeaves
#print axioms DeltaReduce.FamilyApply.leavesRetainCount
#print axioms DeltaReduce.FamilyApply.everyLeafComputed
#print axioms DeltaReduce.FamilyApply.allLeavesConstructible
#print axioms DeltaReduce.FamilyApply.everyLeafCanonical
#print axioms DeltaReduce.FamilyApply.aggregateConstructedCanonical
#print axioms DeltaReduce.FamilyApply.Projection
#print axioms DeltaReduce.FamilyApply.project
#print axioms DeltaReduce.FamilyApply.Projection.aggregateFields
#print axioms DeltaReduce.FamilyApply.Projection.aggregate
#print axioms DeltaReduce.FamilyApply.Projection.fields
#print axioms DeltaReduce.FamilyApply.Projection.value
#print axioms DeltaReduce.FamilyApply.Checked
#print axioms DeltaReduce.FamilyApply.check
#print axioms DeltaReduce.FamilyApply.computedWholeBody
#print axioms DeltaReduce.FamilyApply.allAggregateFields
#print axioms DeltaReduce.FamilyApply.allApplyFields
#print axioms DeltaReduce.FamilyApply.entireAuthorityAndAggregate
#print axioms DeltaReduce.FamilyApply.originalLeafCount
#print axioms DeltaReduce.FamilyApply.originalCertifiedCorpus
#print axioms DeltaReduce.FamilyApply.originalCertificate
#print axioms DeltaReduce.FamilyApply.actualNextVectors
#print axioms DeltaReduce.FamilyApply.noInventedCheckpoint
#print axioms DeltaReduce.FamilyApply.coordinateComputesNextCells
#print axioms DeltaReduce.FamilyApply.nextTablesCanonical
#print axioms DeltaReduce.FamilyApply.constructedBodyCanonical
#print axioms DeltaReduce.FamilyApply.checkedFromConstructed
#print axioms DeltaReduce.FamilyGuards.fitsWiden
#print axioms DeltaReduce.FamilyGuards.fractionWiden
#print axioms DeltaReduce.FamilyGuards.addWiden
#print axioms DeltaReduce.FamilyGuards.parameterPrefixesWiden
#print axioms DeltaReduce.FamilyGuards.parameterWiden
#print axioms DeltaReduce.FamilyGuards.lcmWiden
#print axioms DeltaReduce.FamilyGuards.widenPlan
#print axioms DeltaReduce.FamilyGuards.mixStepWiden
#print axioms DeltaReduce.FamilyGuards.mixPrefixesWiden
#print axioms DeltaReduce.FamilyGuards.mixWiden
#print axioms DeltaReduce.FamilyGuards.widenGradient
#print axioms DeltaReduce.FamilyGuards.gradientTraceWiden
#print axioms DeltaReduce.FamilyGuards.optimizerWiden
#print axioms DeltaReduce.FamilyGuards.optimizerTraceWiden
#print axioms DeltaReduce.FamilyGuards.widenApply
#print axioms DeltaReduce.FamilyGuards.accumulatorAsymmetric
#print axioms DeltaReduce.FamilyGuards.nativeBoundsContained
#print axioms DeltaReduce.FamilyGuards.symmetricResultIncludesMinimum
#print axioms DeltaReduce.FamilyGuards.nativeParameterAtPublicWidth
#print axioms DeltaReduce.FamilyGuards.nativeApplyAtPublicWidth
#print axioms DeltaReduce.FamilyGuards.nativeApplyOutputsPreserved
#print axioms DeltaReduce.FamilyGuards.SequenceSafe
#print axioms DeltaReduce.FamilyGuards.PublicSequence
#print axioms DeltaReduce.FamilyGuards.sequenceItems
#print axioms DeltaReduce.FamilyGuards.sequencePrefixes
#print axioms DeltaReduce.FamilyGuards.publicSequenceFromRecurrence
#print axioms DeltaReduce.FamilyGuards.coefficientSequence
#print axioms DeltaReduce.FamilyGuards.productSequence
#print axioms DeltaReduce.FamilyGuards.nativeParameterPublicSequences
#print axioms DeltaReduce.FamilyGuards.PublicConversion
#print axioms DeltaReduce.FamilyGuards.conversionIsPublicGuard
#print axioms DeltaReduce.FamilyGuards.PublicOptimizerValues
#print axioms DeltaReduce.FamilyGuards.publicOptimizerSubsequence
#print axioms DeltaReduce.FamilyGuards.optimizerIsPublicGuard
#print axioms DeltaReduce.FamilyGuards.mixtureProducts
#print axioms DeltaReduce.FamilyGuards.mixtureSequence
#print axioms DeltaReduce.FamilyGuards.nativeApplyPublicGuards
#print axioms DeltaReduce.FamilyGuards.conversionCoordinate
#print axioms DeltaReduce.FamilyGuards.nativeConversionPublicGuard
#print axioms DeltaReduce.FamilyGuards.exactAccumulateIsSum
#print axioms DeltaReduce.FamilyGuards.nativeParameterResultGuard
#print axioms DeltaReduce.FamilyGuards.derivePlanComplete
#print axioms DeltaReduce.FamilyGuards.extractColumnComplete
#print axioms DeltaReduce.FamilyGuards.deriveGradientComplete
#print axioms DeltaReduce.FamilyGuards.deriveGradientsComplete
#print axioms DeltaReduce.FamilyGuards.optimizerVectorsComplete
#print axioms DeltaReduce.FamilyGuards.deriveApplyComplete
#print axioms DeltaReduce.FamilyGuards.nativeConversions
#print axioms DeltaReduce.FamilyGuards.checkConversionsComplete
#print axioms DeltaReduce.FamilyGuards.nativePublicArithmetic
#print axioms DeltaReduce.FamilyGuards.nativePublicArithmeticCheck
#print axioms DeltaReduce.FamilyGuards.magnitudeRound
#print axioms DeltaReduce.FamilyGuards.magnitudeRoundExact
#print axioms DeltaReduce.FamilyGuards.NativeRoundValid
#print axioms DeltaReduce.FamilyGuards.checkedNativeRound
#print axioms DeltaReduce.FamilyGuards.nativeRoundSound
#print axioms DeltaReduce.FamilyGuards.WireWeight
#print axioms DeltaReduce.FamilyGuards.originalFractionFits
#print axioms DeltaReduce.FamilyGuards.checkedI64
#print axioms DeltaReduce.FamilyGuards.i64Sound
#print axioms DeltaReduce.FamilyGuards.nativeOptimizer
#print axioms DeltaReduce.FamilyGuards.nativeOptimizerSound
#print axioms DeltaReduce.FamilyGuards.nativeOptimizerPublicGuard
#print axioms DeltaReduce.FamilyGuards.nativeOptimizerVector
#print axioms DeltaReduce.FamilyGuards.nativeVectorShape
#print axioms DeltaReduce.FamilyGuards.nativeVectorAt
#print axioms DeltaReduce.FamilyGuards.OriginalOptimizer
#print axioms DeltaReduce.FamilyGuards.checkOriginalOptimizer
#print axioms DeltaReduce.FamilyGuards.originalOptimizerSource
#print axioms DeltaReduce.FamilyGuards.originalOptimizerEveryCoordinate
#print axioms DeltaReduce.FamilyGuards.nativeLcmScale
#print axioms DeltaReduce.FamilyGuards.wireMixtureWeightFits
#print axioms DeltaReduce.FamilyGuards.lcmPrefixesFromFinalBound
#print axioms DeltaReduce.FamilyGuards.lcmComputedFromPrefixes
#print axioms DeltaReduce.FamilyGuards.originalMixtureLcmCompletes
#print axioms DeltaReduce.FamilyGuards.checkedOriginalProfileMixtureLcm
#print axioms DeltaReduce.FamilyRoot.Projection
#print axioms DeltaReduce.FamilyRoot.project
#print axioms DeltaReduce.FamilyRoot.Projection.fields
#print axioms DeltaReduce.FamilyRoot.Projection.value
#print axioms DeltaReduce.FamilyRoot.Checked
#print axioms DeltaReduce.FamilyRoot.check
#print axioms DeltaReduce.FamilyRoot.wholeBody
#print axioms DeltaReduce.FamilyRoot.completeFields
#print axioms DeltaReduce.FamilyRoot.constructedCanonical
#print axioms DeltaReduce.FamilyRoot.nativeLeafCount
#print axioms DeltaReduce.FamilyRoot.nativeLeafAt
#print axioms DeltaReduce.FamilyRoot.originalVectorAt
#print axioms DeltaReduce.FamilyRoot.allParents
#print axioms DeltaReduce.FamilyRoot.originalVoteIdentity
#print axioms DeltaReduce.FamilyRoot.constructorTotal
#print axioms DeltaReduce.FamilyRoot.PrimitiveChecks
#print axioms DeltaReduce.FamilyRoot.Joined
#print axioms DeltaReduce.FamilyRoot.join
#print axioms DeltaReduce.FamilyRoot.roundIdentity
#print axioms DeltaReduce.FamilyRoot.entryIdentity
#print axioms DeltaReduce.FamilyRoot.memberIdentity
#print axioms DeltaReduce.FamilyRoot.iscIdentity
#print axioms DeltaReduce.FamilyRoot.seedIdentity
#print axioms DeltaReduce.FamilyRoot.ecIdentity
#print axioms DeltaReduce.FamilyRoot.apcIdentity
#print axioms DeltaReduce.FamilyRoot.sourceParentContext
#print axioms DeltaReduce.FamilyRelation.applyConstructorTotal
#print axioms DeltaReduce.FamilyRelation.selectCoordinates
#print axioms DeltaReduce.FamilyRelation.ArithmeticConfiguration
#print axioms DeltaReduce.FamilyRelation.widthMatches
#print axioms DeltaReduce.FamilyRelation.Inputs
#print axioms DeltaReduce.FamilyRelation.loadInputs
#print axioms DeltaReduce.FamilyRelation.loadedInputsHaveNumericGuards
#print axioms DeltaReduce.FamilyRelation.ParameterBody
#print axioms DeltaReduce.FamilyRelation.loadParameterBody
#print axioms DeltaReduce.FamilyRelation.parameterCandidateUsesOwnInputs
#print axioms DeltaReduce.FamilyRelation.ApplyBody
#print axioms DeltaReduce.FamilyRelation.loadApplyBody
#print axioms DeltaReduce.FamilyRelation.SourceBody
#print axioms DeltaReduce.FamilyRelation.loadSourceBody
#print axioms DeltaReduce.FamilyRelation.Historical
#print axioms DeltaReduce.FamilyRelation.checkHistorical
#print axioms DeltaReduce.FamilyRelation.historicalOriginalIdentity
#print axioms DeltaReduce.FamilyRelation.nonArithmeticRejected
#print axioms DeltaReduce.FamilyRelation.actorBytes
#print axioms DeltaReduce.FamilyRelation.ActorNamespace
#print axioms DeltaReduce.FamilyRelation.checkActors
#print axioms DeltaReduce.FamilyRelation.actorsExactCount
#print axioms DeltaReduce.FamilyRelation.actorHasOriginal
#print axioms DeltaReduce.FamilyRelation.originalHasActor
#print axioms DeltaReduce.FamilyRelation.collectedSameAt
#print axioms DeltaReduce.FamilyRelation.actorAliasesInjective
#print axioms DeltaReduce.FamilyRelation.repeatedActorAliasRejected
#print axioms DeltaReduce.FamilyRelation.PolicyActors
#print axioms DeltaReduce.FamilyRelation.checkPolicyActors
#print axioms DeltaReduce.FamilyRelation.SignerImage
#print axioms DeltaReduce.FamilyRelation.checkSigners
#print axioms DeltaReduce.FamilyRelation.signerThresholdPreserved
#print axioms DeltaReduce.FamilyRelation.signerMembershipPreserved
#print axioms DeltaReduce.FamilyRelation.actualIscQuorumPreserved
#print axioms DeltaReduce.FamilyRelation.CapturedArithmetic
#print axioms DeltaReduce.FamilyRelation.checkOriginal
#print axioms DeltaReduce.FamilyRelation.capturedOriginalBytes
#print axioms DeltaReduce.FamilyRelation.capturedOriginalPosition
#print axioms DeltaReduce.FamilyRelation.capturedOriginalGraph
#print axioms DeltaReduce.FamilyRelation.capturedNoNewProtocolIdentity
#print axioms DeltaReduce.FamilyRelation.originalGuardUnchanged
#print axioms DeltaReduce.FamilyRelation.ConfiguredArithmetic
#print axioms DeltaReduce.FamilyRelation.checkConfiguredArithmetic
#print axioms DeltaReduce.FamilyRelation.configuredSameOriginalPolicy
#print axioms DeltaReduce.FamilyRelation.configuredActorIsOriginal
#print axioms DeltaReduce.FamilyRelation.configuredNoActorDuplication
#print axioms DeltaReduce.FamilyRelation.configuredOriginalCommitteeCount
#print axioms DeltaReduce.FamilyChecks.wideProfile
#print axioms DeltaReduce.FamilyChecks.unsignedDenominatorIsOriginalDomain
#print axioms DeltaReduce.FamilyChecks.unsignedOptimizerComputes
#print axioms DeltaReduce.FamilyChecks.oldProfileAdapterExcludesThisDomain
#print axioms DeltaReduce.FamilyChecks.roundingBothNegativeBranches
#print axioms DeltaReduce.FamilyChecks.nativeMinimumDivisionGuardRetained
#print axioms DeltaReduce.FamilyChecks.zeroLearningDoesNotHideEarlierOverflow
#print axioms DeltaReduce.FamilyChecks.vectorShapeIsExact
#print axioms DeltaReduce.FamilyChecks.originalWidthsStillPreserved
#print axioms DeltaReduce.FamilyChecks.originalCompleteValuesStillReconstruct
