import FamilyChecks
import Checks
#print axioms DeltaReduce.ShardFamily.Layout
#print axioms DeltaReduce.ShardFamily.Selector
#print axioms DeltaReduce.ShardFamily.base
#print axioms DeltaReduce.ShardFamily.select
#print axioms DeltaReduce.ShardFamily.select_self
#print axioms DeltaReduce.ShardFamily.Whole
#print axioms DeltaReduce.ShardFamily.Family
#print axioms DeltaReduce.ShardFamily.project
#print axioms DeltaReduce.ShardFamily.reconstruct
#print axioms DeltaReduce.ShardFamily.reconstruct_values
#print axioms DeltaReduce.ShardFamily.reconstruct_project
#print axioms DeltaReduce.ShardFamily.project_reconstruct
#print axioms DeltaReduce.ShardFamily.injective
#print axioms DeltaReduce.ShardFamily.rows
#print axioms DeltaReduce.ShardFamily.complete_rows
#print axioms DeltaReduce.ShardFamily.exact_rows
#print axioms DeltaReduce.ShardFamily.validateRows
#print axioms DeltaReduce.ShardFamily.validate_exact
#print axioms DeltaReduce.ShardFamily.scalarView
#print axioms DeltaReduce.ShardFamily.one_common
#print axioms DeltaReduce.ShardFamily.common_predicate
#print axioms DeltaReduce.ShardFamily.signer_union
#print axioms DeltaReduce.ShardFamily.all_views_iff
#print axioms DeltaReduce.ShardFamily.ordered
#print axioms DeltaReduce.ShardFamily.flatten
#print axioms DeltaReduce.ShardFamily.original_shard_count
#print axioms DeltaReduce.ShardFamily.complete_ordered_reconstruction
#print axioms DeltaReduce.ManifestFamily.corpusShapes
#print axioms DeltaReduce.ManifestFamily.positiveAndBounded
#print axioms DeltaReduce.ManifestFamily.layout
#print axioms DeltaReduce.ManifestFamily.whole
#print axioms DeltaReduce.ManifestFamily.family
#print axioms DeltaReduce.ManifestFamily.full_reconstruction
#print axioms DeltaReduce.ManifestFamily.bounded_layout
#print axioms DeltaReduce.ManifestFamily.ordered_source
#print axioms DeltaReduce.ManifestFamily.raw_identity
#print axioms DeltaReduce.ManifestFamily.coordinate_source
#print axioms DeltaReduce.ManifestFamily.original
#print axioms DeltaReduce.ManifestFamily.originalWidths
#print axioms DeltaReduce.ManifestFamily.originalCount
#print axioms DeltaReduce.ManifestFamily.originalStarts
#print axioms DeltaReduce.ManifestFamily.originalRoundtrip
#print axioms DeltaReduce.ManifestFamily.originalFullValues
#print axioms DeltaReduce.ManifestFamily.originalNoNewObjects
#print axioms DeltaReduce.NativeFamily.single
#print axioms DeltaReduce.NativeFamily.parameterLayout
#print axioms DeltaReduce.NativeFamily.parameterSlot
#print axioms DeltaReduce.NativeFamily.parameterWhole
#print axioms DeltaReduce.NativeFamily.parameterFamily
#print axioms DeltaReduce.NativeFamily.parameterRoundtrip
#print axioms DeltaReduce.NativeFamily.parameterCoordinate
#print axioms DeltaReduce.NativeFamily.parameterOriginalRows
#print axioms DeltaReduce.NativeFamily.reconstructedBody
#print axioms DeltaReduce.NativeFamily.completeBodyRecovered
#print axioms DeltaReduce.NativeFamily.originalBodyBytes
#print axioms DeltaReduce.NativeFamily.oldScalarResult
#print axioms DeltaReduce.NativeFamily.parameterFromVote
#print axioms DeltaReduce.NativeFamily.parameterFromVoteEncoded
#print axioms DeltaReduce.NativeFamily.preparedFamily
#print axioms DeltaReduce.NativeFamily.preparedRecordIdentity
#print axioms DeltaReduce.NativeFamily.preparedWholeBodyRecovered
#print axioms DeltaReduce.NativeFamily.preparedOriginalCommand
#print axioms DeltaReduce.NativeFamily.ApplyCell
#print axioms DeltaReduce.NativeFamily.applyCell
#print axioms DeltaReduce.NativeFamily.applyLayout
#print axioms DeltaReduce.NativeFamily.applySlot
#print axioms DeltaReduce.NativeFamily.applyWhole
#print axioms DeltaReduce.NativeFamily.applyFamily
#print axioms DeltaReduce.NativeFamily.applyModelReconstructed
#print axioms DeltaReduce.NativeFamily.applyOriginalHashPreimages
#print axioms DeltaReduce.NativeFamily.applyArithmeticCoordinate
#print axioms DeltaReduce.NativeFamily.certificateSignersUnchanged
#print axioms DeltaReduce.NativeFamily.originalRecordUnchanged
#print axioms DeltaReduce.StateFamily.Layout
#print axioms DeltaReduce.StateFamily.ofValidated
#print axioms DeltaReduce.StateFamily.shards
#print axioms DeltaReduce.StateFamily.globalIndex
#print axioms DeltaReduce.StateFamily.whole
#print axioms DeltaReduce.StateFamily.family
#print axioms DeltaReduce.StateFamily.globalCovered
#print axioms DeltaReduce.StateFamily.contains
#print axioms DeltaReduce.StateFamily.read
#print axioms DeltaReduce.StateFamily.readOriginal
#print axioms DeltaReduce.StateFamily.rebuild
#print axioms DeltaReduce.StateFamily.collectExact
#print axioms DeltaReduce.StateFamily.fullOrderedState
#print axioms DeltaReduce.StateFamily.globalInjective
#print axioms DeltaReduce.StateFamily.exactlyOnce
#print axioms DeltaReduce.StateFamily.nativeLayout
#print axioms DeltaReduce.StateFamily.nativeModelShape
#print axioms DeltaReduce.StateFamily.nativeCell
#print axioms DeltaReduce.StateFamily.nativeValues
#print axioms DeltaReduce.StateFamily.nativeFamily
#print axioms DeltaReduce.StateFamily.nativeCompleteState
#print axioms DeltaReduce.StateFamily.nativeOriginalLayout
#print axioms DeltaReduce.StateFamily.nativeNextVectors
#print axioms DeltaReduce.StateFamily.nativeRebuildHashPreimages
#print axioms DeltaReduce.FamilyTransferChecks.layout
#print axioms DeltaReduce.FamilyTransferChecks.first
#print axioms DeltaReduce.FamilyTransferChecks.last
#print axioms DeltaReduce.FamilyTransferChecks.firstCoordinates
#print axioms DeltaReduce.FamilyTransferChecks.lastCoordinates
#print axioms DeltaReduce.FamilyTransferChecks.original36
#print axioms DeltaReduce.FamilyTransferChecks.firstShard
#print axioms DeltaReduce.FamilyTransferChecks.originalRows
#print axioms DeltaReduce.FamilyTransferChecks.missingRejects
#print axioms DeltaReduce.FamilyTransferChecks.duplicateRejects
#print axioms DeltaReduce.FamilyTransferChecks.swappedRejects
#print axioms DeltaReduce.FamilyTransferChecks.valueRejects
#print axioms DeltaReduce.FamilyTransferChecks.noHiddenCrossShardDependency
#print axioms DeltaReduce.FamilyInputs.Choice
#print axioms DeltaReduce.FamilyInputs.collectExists
#print axioms DeltaReduce.FamilyInputs.Block
#print axioms DeltaReduce.FamilyInputs.loadBlock
#print axioms DeltaReduce.FamilyInputs.Entry
#print axioms DeltaReduce.FamilyInputs.Entries
#print axioms DeltaReduce.FamilyInputs.loadEntries
#print axioms DeltaReduce.FamilyInputs.entryAssignments
#print axioms DeltaReduce.FamilyInputs.Corpus
#print axioms DeltaReduce.FamilyInputs.loadCorpus
#print axioms DeltaReduce.FamilyInputs.blockLoaderComplete
#print axioms DeltaReduce.FamilyInputs.entriesLoaderComplete
#print axioms DeltaReduce.FamilyInputs.corpusLoaderComplete
#print axioms DeltaReduce.FamilyInputs.cellsAt
#print axioms DeltaReduce.FamilyInputs.cellSource
#print axioms DeltaReduce.FamilyInputs.cellsComplete
#print axioms DeltaReduce.FamilyInputs.cellsContributions
#print axioms DeltaReduce.FamilyInputs.scalarRows
#print axioms DeltaReduce.FamilyInputs.selectedRowsExact
#print axioms DeltaReduce.FamilyInputs.entryInput
#print axioms DeltaReduce.FamilyInputs.entryInputComplete
#print axioms DeltaReduce.FamilyInputs.entryInputLocality
#print axioms DeltaReduce.FamilyInputs.entryInputSource
#print axioms DeltaReduce.FamilyInputs.selectedCellHasOriginalBytes
#print axioms DeltaReduce.FamilyInputs.selectedCellNumbers
#print axioms DeltaReduce.FamilyInputs.inputRetainsEligibleOrder
#print axioms DeltaReduce.FamilyInputs.selectedCurrent
#print axioms DeltaReduce.FamilyInputs.selectedCurrentIsFamily
#print axioms DeltaReduce.FamilyInputs.selectedCurrentCellSource
#print axioms DeltaReduce.FamilyInputs.Projected
#print axioms DeltaReduce.FamilyInputs.project
#print axioms DeltaReduce.FamilyInputs.weightPlanLoaderComplete
#print axioms DeltaReduce.FamilyInputs.projectFromComputed
#print axioms DeltaReduce.FamilyInputs.image
#print axioms DeltaReduce.FamilyInputs.encode
#print axioms DeltaReduce.FamilyInputs.completePublicFields
#print axioms DeltaReduce.FamilyInputs.originalNamespaces
#print axioms DeltaReduce.FamilyInputs.projectedQSource
#print axioms DeltaReduce.FamilyInputs.projectedInputOrigin
#print axioms DeltaReduce.FamilyInputs.projectedTicketNames
#print axioms DeltaReduce.FamilyInputs.projectedTicketHasExactShape
#print axioms DeltaReduce.FamilyInputs.projectedTicketWeightValid
#print axioms DeltaReduce.FamilyInputs.projectedQuantumValid
#print axioms DeltaReduce.FamilyInputs.projectedCurrentRange
#print axioms DeltaReduce.FamilyInputs.collectedKeys
#print axioms DeltaReduce.FamilyInputs.projectedDomainNames
#print axioms DeltaReduce.FamilyInputs.projectedDomainShape
#print axioms DeltaReduce.FamilyInputs.projectedDomainPositive
#print axioms DeltaReduce.FamilyInputs.projectedTicketDenominator
#print axioms DeltaReduce.FamilyInputs.projectedTicketDomain
#print axioms DeltaReduce.FamilyInputs.projectedMixtureGuard
#print axioms DeltaReduce.FamilyInputs.projectedCurrentNames
#print axioms DeltaReduce.FamilyInputs.InputNumericGuards
#print axioms DeltaReduce.FamilyInputs.allInputNumericGuards
#print axioms DeltaReduce.FamilyInputs.onlyMember
#print axioms DeltaReduce.FamilyInputs.qAtAgreesWithCell
#print axioms DeltaReduce.FamilyInputs.collectedAtInput
#print axioms DeltaReduce.FamilyInputs.collectInputHasOutput
#print axioms DeltaReduce.FamilyInputs.derivedTicketFilterNames
#print axioms DeltaReduce.FamilyInputs.collectPaired
#print axioms DeltaReduce.FamilyInputs.readImageRow
#print axioms DeltaReduce.FamilyInputs.imageRows
#print axioms DeltaReduce.FamilyInputs.selectedInputIsExposed
#print axioms DeltaReduce.FamilyInputs.exposedTicketForCell
#print axioms DeltaReduce.FamilyInputs.exposedCellValue
#print axioms DeltaReduce.FamilyInputs.publicOrderIsNativeMemberOrder
#print axioms DeltaReduce.FamilyInputs.publicRowsAreSelectedNativeRows
#print axioms DeltaReduce.FamilyInputs.selectedCurrentNames
#print axioms DeltaReduce.FamilyInputs.selectedCurrentAt
#print axioms DeltaReduce.FamilyInputs.activeNames
#print axioms DeltaReduce.FamilyInputs.completeTicket
#print axioms DeltaReduce.FamilyInputs.completeTickets
#print axioms DeltaReduce.FamilyInputs.completionKeepsTicket
#print axioms DeltaReduce.FamilyInputs.completionExactUniverse
#print axioms DeltaReduce.FamilyInputs.completionRetainsActive
#print axioms DeltaReduce.FamilyInputs.completionInactiveIsLatent
#print axioms DeltaReduce.FamilyInputs.memberTickets
#print axioms DeltaReduce.FamilyInputs.completionSelection
#print axioms DeltaReduce.FamilyInputs.completionSelectedRowsExact
#print axioms DeltaReduce.FamilyInputs.completedImage
#print axioms DeltaReduce.FamilyInputs.memberImageRows
#print axioms DeltaReduce.FamilyInputs.completedImageComputesSameRows
#print axioms DeltaReduce.FamilyInputs.completedImageNumericGuards
#print axioms DeltaReduce.FamilyInputs.CompletionCoverage
#print axioms DeltaReduce.FamilyInputs.Completed
#print axioms DeltaReduce.FamilyInputs.complete
#print axioms DeltaReduce.FamilyInputs.completionCheckedExactly
#print axioms DeltaReduce.FamilyInputs.completeFromSource
#print axioms DeltaReduce.FamilyInputs.completedTicketDomain
#print axioms DeltaReduce.FamilyInputs.completedHasNoDuplicateTickets
#print axioms DeltaReduce.FamilyInputs.excludedCellsNeverEnterParameter
#print axioms DeltaReduce.FamilyInputs.OriginalPlanParents
#print axioms DeltaReduce.FamilyInputs.originalParentsFromOld
#print axioms DeltaReduce.FamilyInputs.deriveOriginalPlanRows
#print axioms DeltaReduce.FamilyInputs.originalPlanRowsFromComponents
#print axioms DeltaReduce.FamilyInputs.OriginalPlanSource
#print axioms DeltaReduce.FamilyInputs.prepareOriginalMembers
#print axioms DeltaReduce.FamilyInputs.originalPlanPrepared
#print axioms DeltaReduce.FamilyInputs.originalPlanPreparedFromSource
#print axioms DeltaReduce.FamilyInputs.originalPlanExactMembers
#print axioms DeltaReduce.FamilyInputs.OriginalCoefficientSource
#print axioms DeltaReduce.FamilyInputs.prepareOriginalCoefficients
#print axioms DeltaReduce.FamilyInputs.originalCoefficientsPrepared
#print axioms DeltaReduce.FamilyInputs.originalCoefficientsFromSource
#print axioms DeltaReduce.FamilyInputs.OriginalRowsSource
#print axioms DeltaReduce.FamilyInputs.OriginalVectorSource
#print axioms DeltaReduce.FamilyInputs.prepareOriginalVector
#print axioms DeltaReduce.FamilyInputs.originalVectorPrepared
#print axioms DeltaReduce.FamilyInputs.originalVectorPreparedFromSource
#print axioms DeltaReduce.FamilyInputs.originalRowsFromOld
#print axioms DeltaReduce.FamilyInputs.originalVectorFromOld
#print axioms DeltaReduce.FamilyInputs.originalVectorSourceParts
#print axioms DeltaReduce.FamilyInputs.originalRowsSourceParts
#print axioms DeltaReduce.FamilyInputs.originalSourceRows
#print axioms DeltaReduce.FamilyInputs.originalCoefficientIdentity
#print axioms DeltaReduce.FamilyInputs.originalCoordinateRange
#print axioms DeltaReduce.FamilyInputs.manifestTicket
#print axioms DeltaReduce.FamilyInputs.manifestTicketShape
#print axioms DeltaReduce.FamilyInputs.manifestTicketCoordinate
#print axioms DeltaReduce.FamilyInputs.manifestTicketRange
#print axioms DeltaReduce.FamilyInputs.manifestTicketRetainsOriginal
#print axioms DeltaReduce.FamilyInputs.manifestTicketAllPublicRanges
#print axioms DeltaReduce.FamilyInputs.selectOriginalManifest
#print axioms DeltaReduce.FamilyInputs.selectOriginalManifestFromFamily
#print axioms DeltaReduce.FamilyInputs.readOriginalRowTicket
#print axioms DeltaReduce.FamilyInputs.loadOriginalRowTicket
#print axioms DeltaReduce.FamilyInputs.rowManifestSource
#print axioms DeltaReduce.FamilyInputs.originalRowTicket
#print axioms DeltaReduce.FamilyInputs.originalRowIdentity
#print axioms DeltaReduce.FamilyInputs.originalRowFullPublicRanges
#print axioms DeltaReduce.FamilyInputs.originalRowConstructorTotal
#print axioms DeltaReduce.FamilyInputs.OriginalSelectionFits
#print axioms DeltaReduce.FamilyInputs.originalSelectionFromFamily
#print axioms DeltaReduce.FamilyInputs.originalSelectionCompatible
#print axioms DeltaReduce.FamilyInputs.originalManifestSelectionTotal
#print axioms DeltaReduce.FamilyInputs.originalRowSelectionTotal
#print axioms DeltaReduce.FamilyInputs.readOriginalTickets
#print axioms DeltaReduce.FamilyInputs.originalTicketsConstructorTotal
#print axioms DeltaReduce.FamilyInputs.readOriginalTicketIdentity
#print axioms DeltaReduce.FamilyInputs.selectedManifestCellsSource
#print axioms DeltaReduce.FamilyInputs.readOriginalTicketCells
#print axioms DeltaReduce.FamilyInputs.originalTicketsPublicCells
#print axioms DeltaReduce.FamilyInputs.originalTicketsFullOrderedSource
#print axioms DeltaReduce.FamilyInputs.originalShardNames
#print axioms DeltaReduce.FamilyInputs.selectOriginalCurrent
#print axioms DeltaReduce.FamilyInputs.originalCurrentSelectionTotal
#print axioms DeltaReduce.FamilyInputs.originalCurrentKeys
#print axioms DeltaReduce.FamilyInputs.originalCurrentCellSource
#print axioms DeltaReduce.FamilyInputs.originalCurrentAt
#print axioms DeltaReduce.FamilyInputs.originalImageValue
#print axioms DeltaReduce.FamilyInputs.readOriginalImage
#print axioms DeltaReduce.FamilyInputs.originalImageConstructorTotal
#print axioms DeltaReduce.FamilyInputs.originalTicketNumericSource
#print axioms DeltaReduce.FamilyInputs.originalManifestQuantumGuards
#print axioms DeltaReduce.FamilyInputs.originalMixtureDenominator
#print axioms DeltaReduce.FamilyInputs.OriginalProfileNormalized
#print axioms DeltaReduce.FamilyInputs.originalFractionPublic
#print axioms DeltaReduce.FamilyInputs.originalProfileMixture
#print axioms DeltaReduce.FamilyInputs.originalLimitContainsCurrent
#print axioms DeltaReduce.FamilyInputs.originalImageNumericGuards
#print axioms DeltaReduce.FamilyInputs.byteCharacterRoundtrip
#print axioms DeltaReduce.FamilyInputs.originalLabelRoundtrip
#print axioms DeltaReduce.FamilyInputs.originalLabelInjective
#print axioms DeltaReduce.FamilyInputs.collectFilter
#print axioms DeltaReduce.FamilyInputs.collectCompose
#print axioms DeltaReduce.FamilyInputs.selectedManifestCoordinate
#print axioms DeltaReduce.FamilyInputs.readOriginalRowCoordinate
#print axioms DeltaReduce.FamilyInputs.readOriginalRowDomain
#print axioms DeltaReduce.FamilyInputs.originalScalarRows
#print axioms DeltaReduce.FamilyInputs.originalTicketsDomainSelection
#print axioms DeltaReduce.FamilyInputs.collectOnEqual
#print axioms DeltaReduce.FamilyInputs.originalInputRowsAreSourceRows
#print axioms DeltaReduce.FamilyInputs.OriginalNumericConfigurationChecks
#print axioms DeltaReduce.FamilyInputs.OriginalNumericConfiguration
#print axioms DeltaReduce.FamilyInputs.loadOriginalNumericConfiguration
#print axioms DeltaReduce.FamilyInputs.originalNumericConfigurationLoaded
#print axioms DeltaReduce.FamilyInputs.originalNumericConfigurationProfile
#print axioms DeltaReduce.FamilyInputs.originalConfiguredInputTotal
#print axioms DeltaReduce.FamilyInputs.originalConfiguredInputGuards
#print axioms DeltaReduce.FamilyAuthority.configuredAlias
#print axioms DeltaReduce.FamilyAuthority.collectedValueSource
#print axioms DeltaReduce.FamilyAuthority.Projection
#print axioms DeltaReduce.FamilyAuthority.Projection.round
#print axioms DeltaReduce.FamilyAuthority.Projection.isc
#print axioms DeltaReduce.FamilyAuthority.Projection.seed
#print axioms DeltaReduce.FamilyAuthority.Projection.ec
#print axioms DeltaReduce.FamilyAuthority.Projection.apc
#print axioms DeltaReduce.FamilyAuthority.Projection.fields
#print axioms DeltaReduce.FamilyAuthority.Projection.value
#print axioms DeltaReduce.FamilyAuthority.project
#print axioms DeltaReduce.FamilyAuthority.projectedConfiguration
#print axioms DeltaReduce.FamilyAuthority.Checked
#print axioms DeltaReduce.FamilyAuthority.check
#print axioms DeltaReduce.FamilyAuthority.checkedWholeAuthority
#print axioms DeltaReduce.FamilyAuthority.completeAuthorityInventory
#print axioms DeltaReduce.FamilyAuthority.authorityHasAllCheckedInputs
#print axioms DeltaReduce.FamilyAuthority.authorityHasOriginalParent
#print axioms DeltaReduce.FamilyAuthority.authorityHasBoundSchemaAndProfiles
#print axioms DeltaReduce.FamilyAuthority.coefficientUsesBothAPCAndPlan
#print axioms DeltaReduce.FamilyAuthority.seedAndNormUseNativeParents
#print axioms DeltaReduce.FamilyAuthority.exactConstructedParentChain
#print axioms DeltaReduce.FamilyAuthority.canonicalISCRootIsExactEntrySet
#print axioms DeltaReduce.FamilyAuthority.allNativeCommitmentsRetained
#print axioms DeltaReduce.FamilyAuthority.domainAliasComplete
#print axioms DeltaReduce.FamilyAuthority.shardAliasComplete
#print axioms DeltaReduce.FamilyAuthority.currentTableTotal
#print axioms DeltaReduce.FamilyAuthority.completeISCArtifactOrigin
#print axioms DeltaReduce.FamilyAuthority.nativeParentEdgesChecked
#print axioms DeltaReduce.FamilyAuthority.completeNativeParentPayloads
#print axioms DeltaReduce.FamilyAuthority.eligibleMemberSource
#print axioms DeltaReduce.FamilyAuthority.committedMemberSource
#print axioms DeltaReduce.FamilyAuthority.omittedMemberRequiresInputCompletion
#print axioms DeltaReduce.FamilyAuthority.eligibleSetsAreIdentical
#print axioms DeltaReduce.FamilyAuthority.currentTablesFromBoundVectors
#print axioms DeltaReduce.FamilyAuthority.structuredCurrentValuesShareSchema
#print axioms DeltaReduce.FamilyAuthority.authorityEntriesPreserveSource
#print axioms DeltaReduce.FamilyAuthority.canonicalLookup
#print axioms DeltaReduce.FamilyAuthority.canonicalField
#print axioms DeltaReduce.FamilyAuthority.recordKeys
#print axioms DeltaReduce.FamilyAuthority.canonicalRecord
#print axioms DeltaReduce.FamilyAuthority.encodedKey
#print axioms DeltaReduce.FamilyAuthority.insertKeysOrdered
#print axioms DeltaReduce.FamilyAuthority.sortedKeysOrdered
#print axioms DeltaReduce.FamilyAuthority.canonicalSet
#print axioms DeltaReduce.FamilyAuthority.pairKeys
#print axioms DeltaReduce.FamilyAuthority.pairCanonical
#print axioms DeltaReduce.FamilyAuthority.functionCanonicalParts
#print axioms DeltaReduce.FamilyAuthority.functionCanonicalFromParts
#print axioms DeltaReduce.FamilyAuthority.collectProjection
#print axioms DeltaReduce.FamilyAuthority.CanonicalAliases
#print axioms DeltaReduce.FamilyAuthority.namedCanonicalTotal
#print axioms DeltaReduce.FamilyAuthority.canonicalAliasesCongr
#print axioms DeltaReduce.FamilyAuthority.currentTableCanonicalTotal
#print axioms DeltaReduce.FamilyAuthority.vectorTableCanonicalTotal
#print axioms DeltaReduce.FamilyAuthority.decimalCharsBound
#print axioms DeltaReduce.FamilyAuthority.decimalQuoted
#print axioms DeltaReduce.FamilyAuthority.decimalByteRecovery
#print axioms DeltaReduce.FamilyAuthority.encodedNatInjective
#print axioms DeltaReduce.FamilyAuthority.sequenceIndexKeysUnique
#print axioms DeltaReduce.FamilyAuthority.sequenceCanonicalFromPrimitiveKeys
#print axioms DeltaReduce.FamilyAuthority.currentRowsKeys
#print axioms DeltaReduce.FamilyAuthority.currentTableCanonicalSameKeys
#print axioms DeltaReduce.FamilyAuthority.atomLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.headerLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.entryLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.entriesLoaderComplete
#print axioms DeltaReduce.FamilyAuthority.projectFromComputed
#print axioms DeltaReduce.FamilyAuthority.constructedAuthorityCanonical
#print axioms DeltaReduce.FamilyAuthority.checkedAuthorityFromConstructed
#print axioms DeltaReduce.FamilyAuthority.readPublicEscapes
#print axioms DeltaReduce.FamilyAuthority.publicEscapesRoundtrip
#print axioms DeltaReduce.FamilyAuthority.modelEncodedInjective
#print axioms DeltaReduce.FamilyAuthority.canonicalAliasesFromNamespace
#print axioms DeltaReduce.FamilyAuthority.InputEncodingPrimitives
#print axioms DeltaReduce.FamilyAuthority.InputEncodingPrimitives.ticketAliases
#print axioms DeltaReduce.FamilyAuthority.InputEncodingPrimitives.domainAliases
#print axioms DeltaReduce.FamilyAuthority.InputEncodingPrimitives.shardAliases
#print axioms DeltaReduce.FamilyAuthority.inputTablesCanonicalTotal
#print axioms DeltaReduce.FamilyAuthority.inputComponentsTotal
#print axioms DeltaReduce.FamilyAuthority.inputComponentsCanonical
#print axioms DeltaReduce.FamilyAuthority.inputEncoderTotal
#print axioms DeltaReduce.FamilyAuthority.collectedNamesAsMap
#print axioms DeltaReduce.FamilyAuthority.namespaceSubset
#print axioms DeltaReduce.FamilyAuthority.authorityConstructorTotal
#print axioms DeltaReduce.FamilyAuthority.originalInputEncoderTotal
#print axioms DeltaReduce.FamilyAuthority.OriginalInput
#print axioms DeltaReduce.FamilyAuthority.loadOriginalInput
#print axioms DeltaReduce.FamilyAuthority.originalInputFromComponents
#print axioms DeltaReduce.FamilyAuthority.originalInputFullNumeric
#print axioms DeltaReduce.FamilyAuthority.originalInputFullCoverage
#print axioms DeltaReduce.FamilyAuthority.originalConfiguredInputLoaded
#print axioms DeltaReduce.FamilyAuthority.OriginalContentName
#print axioms DeltaReduce.FamilyAuthority.OriginalContentName.value
#print axioms DeltaReduce.FamilyAuthority.loadOriginalContentName
#print axioms DeltaReduce.FamilyAuthority.OriginalHeader
#print axioms DeltaReduce.FamilyAuthority.loadOriginalHeader
#print axioms DeltaReduce.FamilyAuthority.originalContentNameLoaded
#print axioms DeltaReduce.FamilyAuthority.originalHeaderLoaded
#print axioms DeltaReduce.FamilyAuthority.Original
#print axioms DeltaReduce.FamilyAuthority.Original.fields
#print axioms DeltaReduce.FamilyAuthority.Original.value
#print axioms DeltaReduce.FamilyAuthority.loadOriginal
#print axioms DeltaReduce.FamilyAuthority.originalAllInputs
#print axioms DeltaReduce.FamilyAuthority.originalAuthorityInventory
#print axioms DeltaReduce.FamilyAuthority.originalAuthorityRetainsParentObjects
#print axioms DeltaReduce.FamilyAuthority.originalRoundCanonical
#print axioms DeltaReduce.FamilyAuthority.originalIscCanonical
#print axioms DeltaReduce.FamilyAuthority.originalSeedCanonical
#print axioms DeltaReduce.FamilyAuthority.originalEcCanonical
#print axioms DeltaReduce.FamilyAuthority.originalApcCanonical
#print axioms DeltaReduce.FamilyAuthority.originalPlanningParentsCanonical
#print axioms DeltaReduce.FamilyAuthority.originalAuthorityCanonical
#print axioms DeltaReduce.FamilyAuthority.originalEarlyNameLoaded
#print axioms DeltaReduce.FamilyAuthority.originalPlanningNameLoaded
#print axioms DeltaReduce.FamilyAuthority.originalEarlyHeaderLoaded
#print axioms DeltaReduce.FamilyAuthority.originalIscLoaded
#print axioms DeltaReduce.FamilyAuthority.originalEcLoaded
#print axioms DeltaReduce.FamilyAuthority.originalApcLoaded
#print axioms DeltaReduce.FamilyAuthority.originalAuthorityLoaded
#print axioms DeltaReduce.FamilyParameter.Projection
#print axioms DeltaReduce.FamilyParameter.project
#print axioms DeltaReduce.FamilyParameter.Projection.fields
#print axioms DeltaReduce.FamilyParameter.Projection.body
#print axioms DeltaReduce.FamilyParameter.Checked
#print axioms DeltaReduce.FamilyParameter.check
#print axioms DeltaReduce.FamilyParameter.computedWholeBody
#print axioms DeltaReduce.FamilyParameter.allFields
#print axioms DeltaReduce.FamilyParameter.entireAuthority
#print axioms DeltaReduce.FamilyParameter.entireParents
#print axioms DeltaReduce.FamilyParameter.sourceBeforeSelection
#print axioms DeltaReduce.FamilyParameter.exactNativeCoordinate
#print axioms DeltaReduce.FamilyParameter.publicCoordinateChecked
#print axioms DeltaReduce.FamilyParameter.samePublicInputsComputeBody
#print axioms DeltaReduce.FamilyParameter.actualInputImageComputesBody
#print axioms DeltaReduce.FamilyParameter.constructedBodyCanonical
#print axioms DeltaReduce.FamilyParameter.sourceAliases
#print axioms DeltaReduce.FamilyParameter.originalBodyUnchanged
#print axioms DeltaReduce.FamilyParameter.sameFrame
#print axioms DeltaReduce.FamilyParameter.originalNamespaces
#print axioms DeltaReduce.FamilyParameter.originalEntry
#print axioms DeltaReduce.FamilyParameter.parameterConstructorTotal
#print axioms DeltaReduce.FamilyParameter.parameterFromAuthority
#print axioms DeltaReduce.FamilyParameter.checkedParameterFromAuthority
#print axioms DeltaReduce.FamilyParameter.OriginalVector
#print axioms DeltaReduce.FamilyParameter.originalVector
#print axioms DeltaReduce.FamilyParameter.originalVectorSource
#print axioms DeltaReduce.FamilyParameter.publicParameterRows
#print axioms DeltaReduce.FamilyParameter.originalSlicesTotal
#print axioms DeltaReduce.FamilyParameter.originalLeavesTotal
#print axioms DeltaReduce.FamilyParameter.originalVectorTotal
#print axioms DeltaReduce.FamilyParameter.OriginalProjection
#print axioms DeltaReduce.FamilyParameter.projectOriginal
#print axioms DeltaReduce.FamilyParameter.OriginalProjection.fields
#print axioms DeltaReduce.FamilyParameter.OriginalProjection.body
#print axioms DeltaReduce.FamilyParameter.checkOriginal
#print axioms DeltaReduce.FamilyParameter.originalProjectionLoaded
#print axioms DeltaReduce.FamilyParameter.originalCheckFromCanonical
#print axioms DeltaReduce.FamilyParameter.originalFullVectorRetained
#print axioms DeltaReduce.FamilyParameter.originalValueFromOwnInputs
#print axioms DeltaReduce.FamilyParameter.originalBodyFieldInventory
#print axioms DeltaReduce.FamilyParameter.originalBodyContainsWholeAuthority
#print axioms DeltaReduce.FamilyParameter.originalBodyCanonical
#print axioms DeltaReduce.FamilyParameter.exactVectorLength
#print axioms DeltaReduce.FamilyParameter.exactVectorCoordinate
#print axioms DeltaReduce.FamilyParameter.scalarRowsFromSlices
#print axioms DeltaReduce.FamilyParameter.originalVectorCoordinate
#print axioms DeltaReduce.FamilyParameter.originalBlockMatches
#print axioms DeltaReduce.FamilyParameter.OriginalLeaf
#print axioms DeltaReduce.FamilyParameter.loadOriginalLeaf
#print axioms DeltaReduce.FamilyParameter.OriginalLeaf.value
#print axioms DeltaReduce.FamilyParameter.originalLeafLoaded
#print axioms DeltaReduce.FamilyParameter.originalLeafRejectsAmbiguous
#print axioms DeltaReduce.FamilyApplyArithmetic.conversion
#print axioms DeltaReduce.FamilyApplyArithmetic.conversionWidthsAgree
#print axioms DeltaReduce.FamilyApplyArithmetic.Converted
#print axioms DeltaReduce.FamilyApplyArithmetic.checkConversion
#print axioms DeltaReduce.FamilyApplyArithmetic.conversionChecksAllProducts
#print axioms DeltaReduce.FamilyApplyArithmetic.Conversions
#print axioms DeltaReduce.FamilyApplyArithmetic.checkConversions
#print axioms DeltaReduce.FamilyApplyArithmetic.everyConversionChecked
#print axioms DeltaReduce.FamilyApplyArithmetic.Checked
#print axioms DeltaReduce.FamilyApplyArithmetic.check
#print axioms DeltaReduce.FamilyApplyArithmetic.outputIdentity
#print axioms DeltaReduce.FamilyApplyArithmetic.originalRowsFromPlacedConvertedValues
#print axioms DeltaReduce.FamilyApplyArithmetic.noCertifiedConversionOmitted
#print axioms DeltaReduce.FamilyApplyArithmetic.originalOutputsMeetModelRange
#print axioms DeltaReduce.FamilyGuards.fitsWiden
#print axioms DeltaReduce.FamilyGuards.fractionWiden
#print axioms DeltaReduce.FamilyGuards.addWiden
#print axioms DeltaReduce.FamilyGuards.parameterPrefixesWiden
#print axioms DeltaReduce.FamilyGuards.parameterWiden
#print axioms DeltaReduce.FamilyGuards.lcmWiden
#print axioms DeltaReduce.FamilyGuards.widenPlan
#print axioms DeltaReduce.FamilyGuards.mixStepWiden
#print axioms DeltaReduce.FamilyGuards.mixPrefixesWiden
#print axioms DeltaReduce.FamilyGuards.mixWiden
#print axioms DeltaReduce.FamilyGuards.widenGradient
#print axioms DeltaReduce.FamilyGuards.gradientTraceWiden
#print axioms DeltaReduce.FamilyGuards.optimizerWiden
#print axioms DeltaReduce.FamilyGuards.optimizerTraceWiden
#print axioms DeltaReduce.FamilyGuards.widenApply
#print axioms DeltaReduce.FamilyGuards.accumulatorAsymmetric
#print axioms DeltaReduce.FamilyGuards.nativeBoundsContained
#print axioms DeltaReduce.FamilyGuards.symmetricResultIncludesMinimum
#print axioms DeltaReduce.FamilyGuards.nativeParameterAtPublicWidth
#print axioms DeltaReduce.FamilyGuards.nativeApplyAtPublicWidth
#print axioms DeltaReduce.FamilyGuards.nativeApplyOutputsPreserved
#print axioms DeltaReduce.FamilyGuards.SequenceSafe
#print axioms DeltaReduce.FamilyGuards.PublicSequence
#print axioms DeltaReduce.FamilyGuards.sequenceItems
#print axioms DeltaReduce.FamilyGuards.sequencePrefixes
#print axioms DeltaReduce.FamilyGuards.publicSequenceFromRecurrence
#print axioms DeltaReduce.FamilyGuards.coefficientSequence
#print axioms DeltaReduce.FamilyGuards.productSequence
#print axioms DeltaReduce.FamilyGuards.nativeParameterPublicSequences
#print axioms DeltaReduce.FamilyGuards.PublicConversion
#print axioms DeltaReduce.FamilyGuards.conversionIsPublicGuard
#print axioms DeltaReduce.FamilyGuards.PublicOptimizerValues
#print axioms DeltaReduce.FamilyGuards.publicOptimizerSubsequence
#print axioms DeltaReduce.FamilyGuards.optimizerIsPublicGuard
#print axioms DeltaReduce.FamilyGuards.mixtureProducts
#print axioms DeltaReduce.FamilyGuards.mixtureSequence
#print axioms DeltaReduce.FamilyGuards.nativeApplyPublicGuards
#print axioms DeltaReduce.FamilyGuards.conversionCoordinate
#print axioms DeltaReduce.FamilyGuards.nativeConversionPublicGuard
#print axioms DeltaReduce.FamilyGuards.exactAccumulateIsSum
#print axioms DeltaReduce.FamilyGuards.nativeParameterResultGuard
#print axioms DeltaReduce.FamilyGuards.derivePlanComplete
#print axioms DeltaReduce.FamilyGuards.extractColumnComplete
#print axioms DeltaReduce.FamilyGuards.deriveGradientComplete
#print axioms DeltaReduce.FamilyGuards.deriveGradientsComplete
#print axioms DeltaReduce.FamilyGuards.optimizerVectorsComplete
#print axioms DeltaReduce.FamilyGuards.deriveApplyComplete
#print axioms DeltaReduce.FamilyGuards.nativeConversions
#print axioms DeltaReduce.FamilyGuards.checkConversionsComplete
#print axioms DeltaReduce.FamilyGuards.nativePublicArithmetic
#print axioms DeltaReduce.FamilyGuards.nativePublicArithmeticCheck
#print axioms DeltaReduce.FamilyGuards.magnitudeRound
#print axioms DeltaReduce.FamilyGuards.magnitudeRoundExact
#print axioms DeltaReduce.FamilyGuards.NativeRoundValid
#print axioms DeltaReduce.FamilyGuards.checkedNativeRound
#print axioms DeltaReduce.FamilyGuards.nativeRoundSound
#print axioms DeltaReduce.FamilyGuards.WireWeight
#print axioms DeltaReduce.FamilyGuards.originalFractionFits
#print axioms DeltaReduce.FamilyGuards.checkedI64
#print axioms DeltaReduce.FamilyGuards.i64Sound
#print axioms DeltaReduce.FamilyGuards.nativeOptimizer
#print axioms DeltaReduce.FamilyGuards.nativeOptimizerSound
#print axioms DeltaReduce.FamilyGuards.nativeOptimizerPublicGuard
#print axioms DeltaReduce.FamilyGuards.nativeOptimizerVector
#print axioms DeltaReduce.FamilyGuards.nativeVectorShape
#print axioms DeltaReduce.FamilyGuards.nativeVectorAt
#print axioms DeltaReduce.FamilyGuards.OriginalOptimizer
#print axioms DeltaReduce.FamilyGuards.checkOriginalOptimizer
#print axioms DeltaReduce.FamilyGuards.originalOptimizerSource
#print axioms DeltaReduce.FamilyGuards.originalOptimizerEveryCoordinate
#print axioms DeltaReduce.FamilyGuards.nativeLcmScale
#print axioms DeltaReduce.FamilyGuards.wireMixtureWeightFits
#print axioms DeltaReduce.FamilyGuards.lcmPrefixesFromFinalBound
#print axioms DeltaReduce.FamilyGuards.lcmComputedFromPrefixes
#print axioms DeltaReduce.FamilyGuards.originalMixtureLcmCompletes
#print axioms DeltaReduce.FamilyGuards.checkedOriginalProfileMixtureLcm
#print axioms DeltaReduce.FamilyGuards.absoluteListSumBound
#print axioms DeltaReduce.FamilyGuards.publicSequenceFromItemBounds
#print axioms DeltaReduce.FamilyGuards.originalParameterSequences
#print axioms DeltaReduce.FamilyGuards.originalParameterTerms
#print axioms DeltaReduce.FamilyGuards.originalSourceParameterGuards
#print axioms DeltaReduce.FamilyGuards.originalSourceCoefficientsArePublicFormula
#print axioms DeltaReduce.FamilyGuards.sequenceSafeFromPrefixes
#print axioms DeltaReduce.FamilyGuards.checkedTermsFromPublicSequence
#print axioms DeltaReduce.FamilyGuards.originalScalarTerms
#print axioms DeltaReduce.FamilyGuards.originalScalarShapes
#print axioms DeltaReduce.FamilyGuards.originalScalarParameterAccepts
#print axioms DeltaReduce.FamilyGuards.originalImageParameterAccepts
#print axioms DeltaReduce.FamilyGuards.originalImageLimit
#print axioms DeltaReduce.FamilyGuards.originalParameterProjectionTotal
#print axioms DeltaReduce.FamilyGuards.originalParameterResultGuard
#print axioms DeltaReduce.FamilyGuards.OriginalApplyMath
#print axioms DeltaReduce.FamilyGuards.checkOriginalApplyMath
#print axioms DeltaReduce.FamilyGuards.OriginalApplyMath.nextModel
#print axioms DeltaReduce.FamilyGuards.OriginalApplyMath.nextOptimizer
#print axioms DeltaReduce.FamilyGuards.originalApplyMathTotal
#print axioms DeltaReduce.FamilyGuards.originalApplyMathShape
#print axioms DeltaReduce.FamilyGuards.originalApplyMathCoordinate
#print axioms DeltaReduce.FamilyGuards.originalApplyCoordinatePublicGuards
#print axioms DeltaReduce.FamilyApply.Leaves
#print axioms DeltaReduce.FamilyApply.projectLeaves
#print axioms DeltaReduce.FamilyApply.leavesRetainCount
#print axioms DeltaReduce.FamilyApply.everyLeafComputed
#print axioms DeltaReduce.FamilyApply.allLeavesConstructible
#print axioms DeltaReduce.FamilyApply.everyLeafCanonical
#print axioms DeltaReduce.FamilyApply.aggregateConstructedCanonical
#print axioms DeltaReduce.FamilyApply.Projection
#print axioms DeltaReduce.FamilyApply.project
#print axioms DeltaReduce.FamilyApply.Projection.aggregateFields
#print axioms DeltaReduce.FamilyApply.Projection.aggregate
#print axioms DeltaReduce.FamilyApply.Projection.fields
#print axioms DeltaReduce.FamilyApply.Projection.value
#print axioms DeltaReduce.FamilyApply.Checked
#print axioms DeltaReduce.FamilyApply.check
#print axioms DeltaReduce.FamilyApply.computedWholeBody
#print axioms DeltaReduce.FamilyApply.allAggregateFields
#print axioms DeltaReduce.FamilyApply.allApplyFields
#print axioms DeltaReduce.FamilyApply.entireAuthorityAndAggregate
#print axioms DeltaReduce.FamilyApply.originalLeafCount
#print axioms DeltaReduce.FamilyApply.originalCertifiedCorpus
#print axioms DeltaReduce.FamilyApply.originalCertificate
#print axioms DeltaReduce.FamilyApply.actualNextVectors
#print axioms DeltaReduce.FamilyApply.noInventedCheckpoint
#print axioms DeltaReduce.FamilyApply.coordinateComputesNextCells
#print axioms DeltaReduce.FamilyApply.nextTablesCanonical
#print axioms DeltaReduce.FamilyApply.constructedBodyCanonical
#print axioms DeltaReduce.FamilyApply.checkedFromConstructed
#print axioms DeltaReduce.FamilyApply.OriginalEntry
#print axioms DeltaReduce.FamilyApply.loadOriginalEntry
#print axioms DeltaReduce.FamilyApply.OriginalEntry.value
#print axioms DeltaReduce.FamilyApply.loadOriginalEntries
#print axioms DeltaReduce.FamilyApply.originalEntrySource
#print axioms DeltaReduce.FamilyApply.originalEntriesExact
#print axioms DeltaReduce.FamilyApply.originalAggregateFields
#print axioms DeltaReduce.FamilyApply.originalAggregate
#print axioms DeltaReduce.FamilyApply.OriginalRoot
#print axioms DeltaReduce.FamilyApply.loadOriginalRoot
#print axioms DeltaReduce.FamilyApply.originalRootExact
#print axioms DeltaReduce.FamilyApply.originalRootLoaded
#print axioms DeltaReduce.FamilyApply.originalConvertEntry
#print axioms DeltaReduce.FamilyApply.originalCells
#print axioms DeltaReduce.FamilyApply.OriginalArithmetic
#print axioms DeltaReduce.FamilyApply.loadOriginalArithmetic
#print axioms DeltaReduce.FamilyApply.OriginalApply
#print axioms DeltaReduce.FamilyApply.loadOriginalApply
#print axioms DeltaReduce.FamilyApply.OriginalApply.fields
#print axioms DeltaReduce.FamilyApply.OriginalApply.value
#print axioms DeltaReduce.FamilyApply.originalApplyFullNextVectors
#print axioms DeltaReduce.FamilyApply.originalApplyFieldInventory
#print axioms DeltaReduce.FamilyApply.originalAggregateCanonical
#print axioms DeltaReduce.FamilyApply.originalNextTablesCanonical
#print axioms DeltaReduce.FamilyApply.originalVectorCanonical
#print axioms DeltaReduce.FamilyApply.originalApplyCanonical
#print axioms DeltaReduce.FamilyApply.checkOriginalApply
#print axioms DeltaReduce.FamilyApply.originalApplyWholeCandidate
#print axioms DeltaReduce.FamilyApply.originalUniqueCellLoaded
#print axioms DeltaReduce.FamilyApply.originalPlacedCoordinatesLoaded
#print axioms DeltaReduce.FamilyApply.originalDomainVectorsLoaded
#print axioms DeltaReduce.FamilyApply.originalApplyRowsLoaded
#print axioms DeltaReduce.FamilyApply.originalArithmeticLoaded
#print axioms DeltaReduce.FamilyApply.originalApplyLoaded
#print axioms DeltaReduce.FamilyApply.originalApplyCheckedFromConstructed
#print axioms DeltaReduce.FamilyApply.originalConversionPublicGuards
#print axioms DeltaReduce.FamilyApply.originalEveryEntryConverted
#print axioms DeltaReduce.FamilyApply.originalEmbeddedCurrentSource
#print axioms DeltaReduce.FamilyApply.originalCoordinateComputesNextCells
#print axioms DeltaReduce.FamilyRoot.Projection
#print axioms DeltaReduce.FamilyRoot.project
#print axioms DeltaReduce.FamilyRoot.Projection.fields
#print axioms DeltaReduce.FamilyRoot.Projection.value
#print axioms DeltaReduce.FamilyRoot.Checked
#print axioms DeltaReduce.FamilyRoot.check
#print axioms DeltaReduce.FamilyRoot.wholeBody
#print axioms DeltaReduce.FamilyRoot.completeFields
#print axioms DeltaReduce.FamilyRoot.constructedCanonical
#print axioms DeltaReduce.FamilyRoot.nativeLeafCount
#print axioms DeltaReduce.FamilyRoot.nativeLeafAt
#print axioms DeltaReduce.FamilyRoot.originalVectorAt
#print axioms DeltaReduce.FamilyRoot.allParents
#print axioms DeltaReduce.FamilyRoot.originalVoteIdentity
#print axioms DeltaReduce.FamilyRoot.constructorTotal
#print axioms DeltaReduce.FamilyRoot.PrimitiveChecks
#print axioms DeltaReduce.FamilyRoot.Joined
#print axioms DeltaReduce.FamilyRoot.join
#print axioms DeltaReduce.FamilyRoot.roundIdentity
#print axioms DeltaReduce.FamilyRoot.entryIdentity
#print axioms DeltaReduce.FamilyRoot.memberIdentity
#print axioms DeltaReduce.FamilyRoot.iscIdentity
#print axioms DeltaReduce.FamilyRoot.seedIdentity
#print axioms DeltaReduce.FamilyRoot.ecIdentity
#print axioms DeltaReduce.FamilyRoot.apcIdentity
#print axioms DeltaReduce.FamilyRoot.sourceParentContext
#print axioms DeltaReduce.FamilyRelation.applyConstructorTotal
#print axioms DeltaReduce.FamilyRelation.selectCoordinates
#print axioms DeltaReduce.FamilyRelation.ArithmeticConfiguration
#print axioms DeltaReduce.FamilyRelation.widthMatches
#print axioms DeltaReduce.FamilyRelation.Inputs
#print axioms DeltaReduce.FamilyRelation.loadInputs
#print axioms DeltaReduce.FamilyRelation.inputsLoaderComplete
#print axioms DeltaReduce.FamilyRelation.loadedCompleteInputsHaveNumericGuards
#print axioms DeltaReduce.FamilyRelation.loadedInputsHaveNumericGuards
#print axioms DeltaReduce.FamilyRelation.ParameterBody
#print axioms DeltaReduce.FamilyRelation.loadParameterBody
#print axioms DeltaReduce.FamilyRelation.parameterBodyConstructorTotal
#print axioms DeltaReduce.FamilyRelation.parameterCandidateUsesOwnInputs
#print axioms DeltaReduce.FamilyRelation.parameterCandidateUsesCompleteInputs
#print axioms DeltaReduce.FamilyRelation.ApplyBody
#print axioms DeltaReduce.FamilyRelation.loadApplyBody
#print axioms DeltaReduce.FamilyRelation.applyBodyFromConstructed
#print axioms DeltaReduce.FamilyRelation.SourceBody
#print axioms DeltaReduce.FamilyRelation.loadSourceBody
#print axioms DeltaReduce.FamilyRelation.Historical
#print axioms DeltaReduce.FamilyRelation.checkHistorical
#print axioms DeltaReduce.FamilyRelation.historicalOriginalIdentity
#print axioms DeltaReduce.FamilyRelation.nonArithmeticRejected
#print axioms DeltaReduce.FamilyRelation.actorBytes
#print axioms DeltaReduce.FamilyRelation.ActorNamespace
#print axioms DeltaReduce.FamilyRelation.checkActors
#print axioms DeltaReduce.FamilyRelation.actorsExactCount
#print axioms DeltaReduce.FamilyRelation.actorHasOriginal
#print axioms DeltaReduce.FamilyRelation.originalHasActor
#print axioms DeltaReduce.FamilyRelation.collectedSameAt
#print axioms DeltaReduce.FamilyRelation.actorAliasesInjective
#print axioms DeltaReduce.FamilyRelation.repeatedActorAliasRejected
#print axioms DeltaReduce.FamilyRelation.PolicyActors
#print axioms DeltaReduce.FamilyRelation.checkPolicyActors
#print axioms DeltaReduce.FamilyRelation.SignerImage
#print axioms DeltaReduce.FamilyRelation.checkSigners
#print axioms DeltaReduce.FamilyRelation.signerThresholdPreserved
#print axioms DeltaReduce.FamilyRelation.signerMembershipPreserved
#print axioms DeltaReduce.FamilyRelation.actualIscQuorumPreserved
#print axioms DeltaReduce.FamilyRelation.CapturedArithmetic
#print axioms DeltaReduce.FamilyRelation.checkOriginal
#print axioms DeltaReduce.FamilyRelation.capturedOriginalBytes
#print axioms DeltaReduce.FamilyRelation.capturedOriginalPosition
#print axioms DeltaReduce.FamilyRelation.capturedOriginalGraph
#print axioms DeltaReduce.FamilyRelation.capturedNoNewProtocolIdentity
#print axioms DeltaReduce.FamilyRelation.originalGuardUnchanged
#print axioms DeltaReduce.FamilyRelation.ConfiguredArithmetic
#print axioms DeltaReduce.FamilyRelation.checkConfiguredArithmetic
#print axioms DeltaReduce.FamilyRelation.configuredSameOriginalPolicy
#print axioms DeltaReduce.FamilyRelation.configuredActorIsOriginal
#print axioms DeltaReduce.FamilyRelation.configuredNoActorDuplication
#print axioms DeltaReduce.FamilyRelation.configuredOriginalCommitteeCount
#print axioms DeltaReduce.FamilyChecks.wideProfile
#print axioms DeltaReduce.FamilyChecks.unsignedDenominatorIsOriginalDomain
#print axioms DeltaReduce.FamilyChecks.unsignedOptimizerComputes
#print axioms DeltaReduce.FamilyChecks.oldProfileAdapterExcludesThisDomain
#print axioms DeltaReduce.FamilyChecks.roundingBothNegativeBranches
#print axioms DeltaReduce.FamilyChecks.nativeMinimumDivisionGuardRetained
#print axioms DeltaReduce.FamilyChecks.zeroLearningDoesNotHideEarlierOverflow
#print axioms DeltaReduce.FamilyChecks.vectorShapeIsExact
#print axioms DeltaReduce.FamilyChecks.originalWidthsStillPreserved
#print axioms DeltaReduce.FamilyChecks.originalCompleteValuesStillReconstruct
#print axioms DeltaReduce.FamilyChecks.omittedInput
#print axioms DeltaReduce.FamilyChecks.omittedConfigured
#print axioms DeltaReduce.FamilyChecks.omittedCompletionCoversConfigured
#print axioms DeltaReduce.FamilyChecks.omittedSelectionRecoversOriginalRows
#print axioms DeltaReduce.FamilyChecks.omittedCannotAlterActiveDomain
#print axioms DeltaReduce.FamilyChecks.missingOrDuplicatedConfiguredReject
#print axioms DeltaReduce.FamilyChecks.completedUnsignedImageNumericallyValid
#print axioms DeltaReduce.FamilyChecks.omittedVocabulary
#print axioms DeltaReduce.FamilyChecks.omittedInputPrimitiveNamespaces
#print axioms DeltaReduce.FamilyChecks.completeUnsignedInputEncodes
#print axioms DeltaReduce.FamilyChecks.unsignedCommonDenominatorParameterAccepted
#print axioms DeltaReduce.FamilyChecks.unsignedCommonDenominatorStillChecksEachProduct
#print axioms DeltaReduce.FamilyChecks.directApplyUsesUnsignedProfile
#print axioms DeltaReduce.FamilyChecks.directApplyRejectsUnnormalizedWeights
#print axioms DeltaReduce.FamilyChecks.nativeLabelsRemainInjective
