#include <delta/runtime/vote_codec.hpp>
#include <iostream>
#include <iomanip>
#include <string>
#include <cstdint>
using Bytes=delta::core::canonical::Bytes;
void text(const std::string& s){std::cout<<std::quoted(s);}
std::string hex(const Bytes& b){constexpr char d[]="0123456789abcdef";std::string s;
 for(auto c:b){auto n=std::to_integer<unsigned>(c);s.push_back(d[n>>4U]);s.push_back(d[n&15U]);}return s;}
Bytes unhex(const std::string& s){Bytes b;for(std::size_t i=0;i<s.size();i+=2)
 b.push_back(static_cast<std::byte>(std::stoul(s.substr(i,2),nullptr,16)));return b;}
template<class T,class F>void list(const T& v,F emit){std::cout<<'[';bool first=true;
 for(const auto& x:v){if(!first)std::cout<<',';first=false;emit(x);}std::cout<<']';}

template<class T>void dump_context(const T& x){std::cout<<'{';
text("arithmetic_profile_id");std::cout<<':';text(x.arithmetic_profile_id);
std::cout<<',';
text("height");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.height);
std::cout<<',';
text("parameter_schema_id");std::cout<<':';text(x.parameter_schema_id);
std::cout<<',';
text("round_config_id");std::cout<<':';text(x.round_config_id);
std::cout<<',';
text("round_id");std::cout<<':';text(x.round_id);
std::cout<<',';
text("validator_epoch_id");std::cout<<':';text(x.validator_epoch_id);
std::cout<<',';
text("view");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.view);
std::cout<<'}';}
template<class T>void dump_rational(const T& x){std::cout<<'{';
text("numerator");std::cout<<':';std::cout<<static_cast<std::int64_t>(x.numerator);
std::cout<<',';
text("denominator");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.denominator);
std::cout<<'}';}
template<class T>void dump_tuple(const T& x){std::cout<<'{';
text("availability_certificate_id");std::cout<<':';text(x.availability_certificate_id);
std::cout<<',';
text("commitment_id");std::cout<<':';text(x.commitment_id);
std::cout<<',';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("ticket_id");std::cout<<':';text(x.ticket_id);
std::cout<<'}';}
template<class T>void dump_input_set_body(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("input_root");std::cout<<':';text(x.input_root);
std::cout<<',';
text("tuples");std::cout<<':';list(x.tuples,[](const auto& e){dump_tuple(e);});
std::cout<<'}';}
template<class T>void dump_input_set(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("input_root");std::cout<<':';text(x.input_root);
std::cout<<',';
text("quorum_threshold");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.quorum_threshold);
std::cout<<',';
text("signer_ids");std::cout<<':';list(x.signer_ids,[](const auto& e){text(e);});
std::cout<<',';
text("tuples");std::cout<<':';list(x.tuples,[](const auto& e){dump_tuple(e);});
std::cout<<'}';}
template<class T>void dump_seed(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("seed_id");std::cout<<':';text(x.seed_id);
std::cout<<',';
text("seed_profile_id");std::cout<<':';text(x.seed_profile_id);
std::cout<<',';
text("share_ids");std::cout<<':';list(x.share_ids,[](const auto& e){text(e);});
std::cout<<'}';}
template<class T>void dump_norm_entry(const T& x){std::cout<<'{';
text("scale_denominator");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.scale_denominator);
std::cout<<',';
text("squared_norm");std::cout<<':';text(x.squared_norm);
std::cout<<',';
text("ticket_id");std::cout<<':';text(x.ticket_id);
std::cout<<'}';}
template<class T>void dump_norm(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("entries");std::cout<<':';list(x.entries,[](const auto& e){dump_norm_entry(e);});
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("norm_root");std::cout<<':';text(x.norm_root);
std::cout<<'}';}
template<class T>void dump_eligibility_entry(const T& x){std::cout<<'{';
text("accepted");std::cout<<':';std::cout<<(x.accepted?"true":"false");
std::cout<<',';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("gamma");std::cout<<':';dump_rational(x.gamma);
std::cout<<',';
text("reason_code");std::cout<<':';text(x.reason_code);
std::cout<<',';
text("ticket_id");std::cout<<':';text(x.ticket_id);
std::cout<<'}';}
template<class T>void dump_eligibility(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("entries");std::cout<<':';list(x.entries,[](const auto& e){dump_eligibility_entry(e);});
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("norm_evidence_id");std::cout<<':';text(x.norm_evidence_id);
std::cout<<',';
text("quorum_threshold");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.quorum_threshold);
std::cout<<',';
text("robust_profile_id");std::cout<<':';text(x.robust_profile_id);
std::cout<<',';
text("signer_ids");std::cout<<':';list(x.signer_ids,[](const auto& e){text(e);});
std::cout<<'}';}
template<class T>void dump_eligibility_body(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("entries");std::cout<<':';list(x.entries,[](const auto& e){dump_eligibility_entry(e);});
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("norm_evidence_id");std::cout<<':';text(x.norm_evidence_id);
std::cout<<',';
text("robust_profile_id");std::cout<<':';text(x.robust_profile_id);
std::cout<<',';
text("seed_transcript_id");std::cout<<':';text(x.seed_transcript_id);
std::cout<<'}';}
template<class T>void dump_finalized_eligibility(const T& x){std::cout<<'{';
text("certificate");std::cout<<':';dump_eligibility(x.certificate);
std::cout<<',';
text("seed_transcript_id");std::cout<<':';text(x.seed_transcript_id);
std::cout<<'}';}
template<class T>void dump_bucket(const T& x){std::cout<<'{';
text("bucket_id");std::cout<<':';text(x.bucket_id);
std::cout<<',';
text("ticket_id");std::cout<<':';text(x.ticket_id);
std::cout<<'}';}
template<class T>void dump_weight(const T& x){std::cout<<'{';
text("alpha");std::cout<<':';dump_rational(x.alpha);
std::cout<<',';
text("ticket_id");std::cout<<':';text(x.ticket_id);
std::cout<<'}';}
template<class T>void dump_plan(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("accumulator_proof_id");std::cout<<':';text(x.accumulator_proof_id);
std::cout<<',';
text("bucket_assignments");std::cout<<':';list(x.bucket_assignments,[](const auto& e){dump_bucket(e);});
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("iteration_count");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.iteration_count);
std::cout<<',';
text("quorum_threshold");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.quorum_threshold);
std::cout<<',';
text("seed_transcript_id");std::cout<<':';text(x.seed_transcript_id);
std::cout<<',';
text("signer_ids");std::cout<<':';list(x.signer_ids,[](const auto& e){text(e);});
std::cout<<',';
text("transcript_root");std::cout<<':';text(x.transcript_root);
std::cout<<',';
text("weights");std::cout<<':';list(x.weights,[](const auto& e){dump_weight(e);});
std::cout<<'}';}
template<class T>void dump_plan_body(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("accumulator_proof_id");std::cout<<':';text(x.accumulator_proof_id);
std::cout<<',';
text("bucket_assignments");std::cout<<':';list(x.bucket_assignments,[](const auto& e){dump_bucket(e);});
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("iteration_count");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.iteration_count);
std::cout<<',';
text("seed_transcript_id");std::cout<<':';text(x.seed_transcript_id);
std::cout<<',';
text("transcript_root");std::cout<<':';text(x.transcript_root);
std::cout<<',';
text("weights");std::cout<<':';list(x.weights,[](const auto& e){dump_weight(e);});
std::cout<<'}';}
template<class T>void dump_shard_key(const T& x){std::cout<<'{';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("shard_id");std::cout<<':';text(x.shard_id);
std::cout<<'}';}
template<class T>void dump_parameter(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("aggregation_plan_certificate_id");std::cout<<':';text(x.aggregation_plan_certificate_id);
std::cout<<',';
text("denominator");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.denominator);
std::cout<<',';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("input_leaf_ids");std::cout<<':';list(x.input_leaf_ids,[](const auto& e){text(e);});
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("quorum_threshold");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.quorum_threshold);
std::cout<<',';
text("result_numerators");std::cout<<':';list(x.result_numerators,[](const auto& e){text(e);});
std::cout<<',';
text("shard_id");std::cout<<':';text(x.shard_id);
std::cout<<',';
text("signer_ids");std::cout<<':';list(x.signer_ids,[](const auto& e){text(e);});
std::cout<<'}';}
template<class T>void dump_parameter_body(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("aggregation_plan_certificate_id");std::cout<<':';text(x.aggregation_plan_certificate_id);
std::cout<<',';
text("denominator");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.denominator);
std::cout<<',';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("input_leaf_ids");std::cout<<':';list(x.input_leaf_ids,[](const auto& e){text(e);});
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("result_numerators");std::cout<<':';list(x.result_numerators,[](const auto& e){text(e);});
std::cout<<',';
text("shard_id");std::cout<<':';text(x.shard_id);
std::cout<<',';
text("vote_context_id");std::cout<<':';text(x.vote_context_id);
std::cout<<'}';}
template<class T>void dump_root_leaf(const T& x){std::cout<<'{';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("parameter_shard_qc_id");std::cout<<':';text(x.parameter_shard_qc_id);
std::cout<<',';
text("shard_id");std::cout<<':';text(x.shard_id);
std::cout<<'}';}
template<class T>void dump_root(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("aggregation_plan_certificate_id");std::cout<<':';text(x.aggregation_plan_certificate_id);
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("leaves");std::cout<<':';list(x.leaves,[](const auto& e){dump_root_leaf(e);});
std::cout<<',';
text("merkle_root");std::cout<<':';text(x.merkle_root);
std::cout<<',';
text("quorum_threshold");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.quorum_threshold);
std::cout<<',';
text("required_keys");std::cout<<':';list(x.required_keys,[](const auto& e){dump_shard_key(e);});
std::cout<<',';
text("signer_ids");std::cout<<':';list(x.signer_ids,[](const auto& e){text(e);});
std::cout<<'}';}
template<class T>void dump_root_body(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("aggregation_plan_certificate_id");std::cout<<':';text(x.aggregation_plan_certificate_id);
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("leaves");std::cout<<':';list(x.leaves,[](const auto& e){dump_root_leaf(e);});
std::cout<<',';
text("merkle_root");std::cout<<':';text(x.merkle_root);
std::cout<<',';
text("required_keys");std::cout<<':';list(x.required_keys,[](const auto& e){dump_shard_key(e);});
std::cout<<'}';}
template<class T>void dump_domain_weight(const T& x){std::cout<<'{';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("pi");std::cout<<':';dump_rational(x.pi);
std::cout<<'}';}
template<class T>void dump_apply_profile(const T& x){std::cout<<'{';
text("accumulator_proof_id");std::cout<<':';text(x.accumulator_proof_id);
std::cout<<',';
text("domain_weights");std::cout<<':';list(x.domain_weights,[](const auto& e){dump_domain_weight(e);});
std::cout<<',';
text("learning_rate");std::cout<<':';dump_rational(x.learning_rate);
std::cout<<',';
text("momentum");std::cout<<':';dump_rational(x.momentum);
std::cout<<',';
text("nesterov");std::cout<<':';std::cout<<(x.nesterov?"true":"false");
std::cout<<',';
text("rounding");std::cout<<':';text(x.rounding);
std::cout<<',';
text("weight_decay");std::cout<<':';dump_rational(x.weight_decay);
std::cout<<'}';}
template<class T>void dump_apply_candidate(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("aggregate_root_qc_id");std::cout<<':';text(x.aggregate_root_qc_id);
std::cout<<',';
text("apply_arithmetic_profile_id");std::cout<<':';text(x.apply_arithmetic_profile_id);
std::cout<<',';
text("next_model_hash");std::cout<<':';text(x.next_model_hash);
std::cout<<',';
text("next_model_values");std::cout<<':';list(x.next_model_values,[](const auto& e){text(e);});
std::cout<<',';
text("next_optimizer_hash");std::cout<<':';text(x.next_optimizer_hash);
std::cout<<',';
text("next_optimizer_values");std::cout<<':';list(x.next_optimizer_values,[](const auto& e){text(e);});
std::cout<<',';
text("parent_checkpoint_id");std::cout<<':';text(x.parent_checkpoint_id);
std::cout<<',';
text("parent_optimizer_hash");std::cout<<':';text(x.parent_optimizer_hash);
std::cout<<'}';}
template<class T>void dump_apply_qc(const T& x){std::cout<<'{';
text("context");std::cout<<':';dump_context(x.context);
std::cout<<',';
text("aggregate_root_qc_id");std::cout<<':';text(x.aggregate_root_qc_id);
std::cout<<',';
text("apply_arithmetic_profile_id");std::cout<<':';text(x.apply_arithmetic_profile_id);
std::cout<<',';
text("apply_candidate_id");std::cout<<':';text(x.apply_candidate_id);
std::cout<<',';
text("next_model_hash");std::cout<<':';text(x.next_model_hash);
std::cout<<',';
text("next_optimizer_hash");std::cout<<':';text(x.next_optimizer_hash);
std::cout<<',';
text("parent_checkpoint_id");std::cout<<':';text(x.parent_checkpoint_id);
std::cout<<',';
text("quorum_threshold");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.quorum_threshold);
std::cout<<',';
text("signer_ids");std::cout<<':';list(x.signer_ids,[](const auto& e){text(e);});
std::cout<<'}';}
template<class T>void dump_finalized_apply(const T& x){std::cout<<'{';
text("certificate");std::cout<<':';dump_apply_qc(x.certificate);
std::cout<<',';
text("candidate");std::cout<<':';dump_apply_candidate(x.candidate);
std::cout<<'}';}
template<class T>void dump_timeout(const T& x){std::cout<<'{';
text("round_id");std::cout<<':';text(x.round_id);
std::cout<<',';
text("height");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.height);
std::cout<<',';
text("view");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.view);
std::cout<<'}';}
template<class T>void dump_view_change(const T& x){std::cout<<'{';
text("round_id");std::cout<<':';text(x.round_id);
std::cout<<',';
text("height");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.height);
std::cout<<',';
text("from_view");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.from_view);
std::cout<<',';
text("to_view");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.to_view);
std::cout<<',';
text("soft_deadline_tick");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.soft_deadline_tick);
std::cout<<'}';}
template<class T>void dump_abort_request(const T& x){std::cout<<'{';
text("round_id");std::cout<<':';text(x.round_id);
std::cout<<',';
text("reason_code");std::cout<<':';text(x.reason_code);
std::cout<<'}';}
template<class T>void dump_abort_body(const T& x){std::cout<<'{';
text("round_id");std::cout<<':';text(x.round_id);
std::cout<<',';
text("validator_epoch_id");std::cout<<':';text(x.validator_epoch_id);
std::cout<<',';
text("height");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.height);
std::cout<<',';
text("view");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.view);
std::cout<<',';
text("hard_deadline_tick");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.hard_deadline_tick);
std::cout<<',';
text("parent_checkpoint_id");std::cout<<':';text(x.parent_checkpoint_id);
std::cout<<',';
text("reason_code");std::cout<<':';text(x.reason_code);
std::cout<<',';
text("round_config_ids");std::cout<<':';list(x.round_config_ids,[](const auto& e){text(e);});
std::cout<<',';
text("input_set_ids");std::cout<<':';list(x.input_set_ids,[](const auto& e){text(e);});
std::cout<<',';
text("eligibility_ids");std::cout<<':';list(x.eligibility_ids,[](const auto& e){text(e);});
std::cout<<',';
text("aggregation_plan_ids");std::cout<<':';list(x.aggregation_plan_ids,[](const auto& e){text(e);});
std::cout<<',';
text("parameter_ids");std::cout<<':';list(x.parameter_ids,[](const auto& e){text(e);});
std::cout<<',';
text("aggregate_root_ids");std::cout<<':';list(x.aggregate_root_ids,[](const auto& e){text(e);});
std::cout<<',';
text("apply_ids");std::cout<<':';list(x.apply_ids,[](const auto& e){text(e);});
std::cout<<'}';}
template<class T>void dump_parents(const T& x){std::cout<<'{';
text("round_config_id");std::cout<<':';text(x.round_config_id);
std::cout<<',';
text("parent_checkpoint_id");std::cout<<':';text(x.parent_checkpoint_id);
std::cout<<',';
text("input_set_certificate_id");std::cout<<':';text(x.input_set_certificate_id);
std::cout<<',';
text("seed_transcript_id");std::cout<<':';text(x.seed_transcript_id);
std::cout<<',';
text("norm_evidence_id");std::cout<<':';text(x.norm_evidence_id);
std::cout<<',';
text("eligibility_certificate_id");std::cout<<':';text(x.eligibility_certificate_id);
std::cout<<',';
text("aggregation_plan_certificate_id");std::cout<<':';text(x.aggregation_plan_certificate_id);
std::cout<<',';
text("parameter_matrix_root");std::cout<<':';text(x.parameter_matrix_root);
std::cout<<',';
text("aggregate_root_certificate_id");std::cout<<':';text(x.aggregate_root_certificate_id);
std::cout<<',';
text("apply_profile_id");std::cout<<':';text(x.apply_profile_id);
std::cout<<',';
text("apply_candidate_id");std::cout<<':';text(x.apply_candidate_id);
std::cout<<',';
text("last_finalized_certificate_id");std::cout<<':';text(x.last_finalized_certificate_id);
std::cout<<',';
text("domain_id");std::cout<<':';text(x.domain_id);
std::cout<<',';
text("shard_id");std::cout<<':';text(x.shard_id);
std::cout<<',';
text("reason_code");std::cout<<':';text(x.reason_code);
std::cout<<'}';}
template<class T>void dump_candidate(const T& x){std::cout<<'{';
text("action");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.action);
std::cout<<',';
text("body_hash");std::cout<<':';text(x.body_hash);
std::cout<<',';
text("context_id");std::cout<<':';text(x.context_id);
std::cout<<',';
text("height");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.height);
std::cout<<',';
text("view");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.view);
std::cout<<',';
text("parents");std::cout<<':';dump_parents(x.parents);
std::cout<<'}';}
template<class T>void dump_snapshot(const T& x){std::cout<<'{';
text("state_id");std::cout<<':';text(x.state_id);
std::cout<<',';
text("parameter_schema_id");std::cout<<':';text(x.parameter_schema_id);
std::cout<<',';
text("arithmetic_profile_id");std::cout<<':';text(x.arithmetic_profile_id);
std::cout<<',';
text("required_accumulator_proof_id");std::cout<<':';text(x.required_accumulator_proof_id);
std::cout<<',';
text("proposed_round_config_ids");std::cout<<':';list(x.proposed_round_config_ids,[](const auto& e){text(e);});
std::cout<<',';
text("finalized_round_config_ids");std::cout<<':';list(x.finalized_round_config_ids,[](const auto& e){text(e);});
std::cout<<',';
text("closed_input_set_ids");std::cout<<':';list(x.closed_input_set_ids,[](const auto& e){text(e);});
std::cout<<',';
text("input_set_bodies");std::cout<<':';list(x.input_set_bodies,[](const auto& e){dump_input_set_body(e);});
std::cout<<',';
text("input_set_certificates");std::cout<<':';list(x.input_set_certificates,[](const auto& e){dump_input_set(e);});
std::cout<<',';
text("finalized_input_set_ids");std::cout<<':';list(x.finalized_input_set_ids,[](const auto& e){text(e);});
std::cout<<',';
text("seed_transcripts");std::cout<<':';list(x.seed_transcripts,[](const auto& e){dump_seed(e);});
std::cout<<',';
text("norm_evidence");std::cout<<':';list(x.norm_evidence,[](const auto& e){dump_norm(e);});
std::cout<<',';
text("eligibility_bodies");std::cout<<':';list(x.eligibility_bodies,[](const auto& e){dump_eligibility_body(e);});
std::cout<<',';
text("eligibility_certificates");std::cout<<':';list(x.eligibility_certificates,[](const auto& e){dump_finalized_eligibility(e);});
std::cout<<',';
text("finalized_eligibility_ids");std::cout<<':';list(x.finalized_eligibility_ids,[](const auto& e){text(e);});
std::cout<<',';
text("aggregation_plan_bodies");std::cout<<':';list(x.aggregation_plan_bodies,[](const auto& e){dump_plan_body(e);});
std::cout<<',';
text("aggregation_plan_certificates");std::cout<<':';list(x.aggregation_plan_certificates,[](const auto& e){dump_plan(e);});
std::cout<<',';
text("finalized_aggregation_plan_ids");std::cout<<':';list(x.finalized_aggregation_plan_ids,[](const auto& e){text(e);});
std::cout<<',';
text("parameter_bodies");std::cout<<':';list(x.parameter_bodies,[](const auto& e){dump_parameter_body(e);});
std::cout<<',';
text("parameter_qcs");std::cout<<':';list(x.parameter_qcs,[](const auto& e){dump_parameter(e);});
std::cout<<',';
text("finalized_parameter_ids");std::cout<<':';list(x.finalized_parameter_ids,[](const auto& e){text(e);});
std::cout<<',';
text("required_parameter_keys");std::cout<<':';list(x.required_parameter_keys,[](const auto& e){dump_shard_key(e);});
std::cout<<',';
text("aggregate_root_bodies");std::cout<<':';list(x.aggregate_root_bodies,[](const auto& e){dump_root_body(e);});
std::cout<<',';
text("aggregate_root_qcs");std::cout<<':';list(x.aggregate_root_qcs,[](const auto& e){dump_root(e);});
std::cout<<',';
text("finalized_aggregate_root_ids");std::cout<<':';list(x.finalized_aggregate_root_ids,[](const auto& e){text(e);});
std::cout<<',';
text("apply_profiles");std::cout<<':';list(x.apply_profiles,[](const auto& e){dump_apply_profile(e);});
std::cout<<',';
text("apply_candidates");std::cout<<':';list(x.apply_candidates,[](const auto& e){dump_apply_candidate(e);});
std::cout<<',';
text("apply_qcs");std::cout<<':';list(x.apply_qcs,[](const auto& e){dump_finalized_apply(e);});
std::cout<<',';
text("finalized_apply_ids");std::cout<<':';list(x.finalized_apply_ids,[](const auto& e){text(e);});
std::cout<<',';
text("timeout_observations");std::cout<<':';list(x.timeout_observations,[](const auto& e){dump_timeout(e);});
std::cout<<',';
text("view_change_bodies");std::cout<<':';list(x.view_change_bodies,[](const auto& e){dump_view_change(e);});
std::cout<<',';
text("abort_requests");std::cout<<':';list(x.abort_requests,[](const auto& e){dump_abort_request(e);});
std::cout<<',';
text("abort_bodies");std::cout<<':';list(x.abort_bodies,[](const auto& e){dump_abort_body(e);});
std::cout<<'}';}
template<class T>void dump_policy(const T& x){std::cout<<'{';
text("local_validator_id");std::cout<<':';text(x.local_validator_id);
std::cout<<',';
text("validator_epoch_id");std::cout<<':';text(x.validator_epoch_id);
std::cout<<',';
text("validator_ids");std::cout<<':';list(x.validator_ids,[](const auto& e){text(e);});
std::cout<<',';
text("role");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.role);
std::cout<<',';
text("round_id");std::cout<<':';text(x.round_id);
std::cout<<',';
text("round_config_id");std::cout<<':';text(x.round_config_id);
std::cout<<',';
text("configured_abort_reason");std::cout<<':';text(x.configured_abort_reason);
std::cout<<',';
text("initial_logical_tick");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.initial_logical_tick);
std::cout<<',';
text("soft_deadline_tick");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.soft_deadline_tick);
std::cout<<',';
text("hard_deadline_tick");std::cout<<':';std::cout<<static_cast<std::uint64_t>(x.hard_deadline_tick);
std::cout<<',';
text("snapshot");std::cout<<':';dump_snapshot(x.snapshot);
std::cout<<',';
text("candidates");std::cout<<':';list(x.candidates,[](const auto& e){dump_candidate(e);});
std::cout<<'}';}
int main(){std::string s;while(std::getline(std::cin,s)){try{
 auto p=delta::runtime::parse_vote_policy_v1(unhex(s));auto b=delta::runtime::encode_vote_policy_v1(p);
 std::cout<<"{\"status\":\"ACCEPT\",\"reencoded_hex\":";text(hex(b));
 std::cout<<",\"value\":";dump_policy(p);std::cout<<"}\n";
 }catch(const std::exception&){std::cout<<"{\"status\":\"REJECT\"}\n";}}}
