schema_version = "1.0.0"
baseline_id = "temurin-25.0.4.1+1-linux-x64"
compatibility_id = "temurin-26.0.2+10-linux-x64"

[[toolchains]]
id = "temurin-25.0.4.1+1-linux-x64"
feature = 25
role = "BASELINE"
version = "25.0.4.1+1"
vendor = "Eclipse Temurin"
architecture = "x64"
os = "linux"
archive_url = "https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.4.1%2B1/OpenJDK25U-jdk_x64_linux_hotspot_25.0.4.1_1.tar.gz"
archive_sha256 = "dbb698396d478e7fa2b1e50f4103324b2a99b90569ee27c33f2261f9215cf41e"
archive_size_bytes = 141329719
license = "GPL-2.0-only WITH Classpath-exception-2.0"

[[toolchains]]
id = "temurin-26.0.2+10-linux-x64"
feature = 26
role = "COMPATIBILITY"
version = "26.0.2+10"
vendor = "Eclipse Temurin"
architecture = "x64"
os = "linux"
archive_url = "https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.2%2B10/OpenJDK26U-jdk_x64_linux_hotspot_26.0.2_10.tar.gz"
archive_sha256 = "56f768372f6ca1e2eb4c5f46b78f627949e8dcfe9c9723926cf45a45faf35802"
archive_size_bytes = 144453933
license = "GPL-2.0-only WITH Classpath-exception-2.0"
