// Display guidance only. Examples never become configuration or authority.
export interface FieldHint {
  labels: string[];
  en: [string, string];
  ru: [string, string];
}
export const fieldHints: FieldHint[] = [
  { labels: ["Interface language"], en: ["Choose the language of labels and help. Identifiers and original evidence remain unchanged.", "English or Русский"], ru: ["Выберите язык интерфейса и подсказок. Идентификаторы и исходные доказательства сохраняют свои значения.", "English или Русский"] },
  { labels: ["Profile name"], en: ["A display name for the shared local settings saved on the application host. This is not a user login.", "Morning demo"], ru: ["Название общих локальных настроек, сохранённых на компьютере приложения. Это не логин пользователя.", "Утренняя демонстрация"] },
  { labels: ["Active campaign"], en: ["Choose the group that will contain your next runs. Previous runs stay in their original campaign.", "Select Morning demo"], ru: ["Выберите группу для следующих запусков. Старые запуски остаются в своей исходной кампании.", "Выберите «Утренняя демонстрация»"] },
  { labels: ["New campaign name"], en: ["Create a named group of runs, up to 80 characters. The group and its run links are saved in your local profile.", "September presentation"], ru: ["Создайте группу запусков с названием до 80 символов. Группа и ссылки на запуски сохраняются в локальном профиле.", "Сентябрьская презентация"] },
  { labels: ["Run name", "Ticket ID"], en: ["Name this training request using 1–64 letters A–Z, digits, underscores or hyphens. An execution ID is assigned separately by the Controller.", "presentation_demo_01"], ru: ["Назовите запрос на обучение: 1–64 латинские буквы, цифры, знаки _ или -. Идентификатор выполнения Controller присвоит отдельно.", "presentation_demo_01"] },
  { labels: ["Model Plugin", "Model plugin"], en: ["Choose the implementation to train or evaluate. The local presentation supports the tabular 10-gene example; other catalog entries require a compatible backend.", "tabular-10gene-phenotype-v1"], ru: ["Выберите реализацию для обучения или оценки. Локальная презентация поддерживает табличный пример с 10 признаками; другим записям каталога нужен совместимый сервер.", "tabular-10gene-phenotype-v1"] },
  { labels: ["Dataset Provider", "Dataset"], en: ["Choose data compatible with the selected model. The local example uses synthetic data and does not require an external download.", "synthetic-10gene-cohort-v1"], ru: ["Выберите данные, совместимые с моделью. Локальный пример использует синтетические данные без внешней загрузки.", "synthetic-10gene-cohort-v1"] },
  { labels: ["Requested Execution Scope", "Requested scope"], en: ["Request an execution scope; the Controller decides whether it is allowed. PLUGIN_BOUNDARY runs the local plugin example. A requested scope is not a qualification claim.", "PLUGIN_BOUNDARY"], ru: ["Запросите режим выполнения; допустимость определяет Controller. PLUGIN_BOUNDARY запускает локальный плагин. Запрошенный режим не подтверждает прохождение квалификации.", "PLUGIN_BOUNDARY"] },
  { labels: ["Catalog backend reference"], en: ["Read-only source revision associated with this catalog. It binds the selection to its catalog version and is filled automatically.", "A 40-character Git revision"], ru: ["Версия исходного кода, связанная с каталогом. Заполняется автоматически и недоступна для редактирования.", "Git-ревизия из 40 символов"] },
  { labels: ["TRAIN_TICKET"], en: ["Ask the Worker to train on a dataset partition. A successful run returns a training receipt.", "Train ticket presentation_demo_01 on partition_00"], ru: ["Запросите обучение Worker на части набора данных. Успешный запуск возвращает квитанцию обучения.", "Обучение по заявке presentation_demo_01 на partition_00"] },
  { labels: ["EVALUATE_CHECKPOINT"], en: ["Evaluate supplied checkpoint coordinates with the selected model and dataset. Use actual compatible coordinates for a meaningful result.", "100, 200, 300, 400 (illustrative coordinates)"], ru: ["Оцените переданные координаты контрольной точки выбранными моделью и данными. Для осмысленного результата нужны реальные совместимые координаты.", "100, 200, 300, 400 (условные координаты)"] },
  { labels: ["MATERIALIZE_DATASET"], en: ["Ask the Controller to prepare a dataset in its cache. This operation does not train a model or produce a training receipt.", "Prepare synthetic-10gene-cohort-v1"], ru: ["Запросите подготовку набора данных в кэше Controller. Операция не обучает модель и не создаёт квитанцию обучения.", "Подготовить synthetic-10gene-cohort-v1"] },
  { labels: ["Partition ID"], en: ["Identify the data partition for this training request. Use 1–64 letters A–Z, digits, underscores or hyphens.", "partition_00"], ru: ["Укажите часть данных для этого запроса обучения. Допустимы 1–64 латинские буквы, цифры, знаки _ или -.", "partition_00"] },
  { labels: ["Checkpoint coordinates (integers)"], en: ["Enter 1–4096 comma-separated signed 32-bit integers from a compatible checkpoint. The model determines the required shape.", "100, 200, 300, 400 (format example only)"], ru: ["Введите через запятую 1–4096 целых знаковых 32-битных чисел из совместимой контрольной точки. Требуемую форму определяет модель.", "100, 200, 300, 400 (только пример формата)"] },
  { labels: ["Cache key (optional)"], en: ["Optional name for prepared data. Use letters A–Z, digits, underscores or hyphens, at most 64 characters. Leave empty to use the default.", "cache_synth_01"], ru: ["Необязательное имя подготовленных данных: до 64 латинских букв, цифр, знаков _ или -. Оставьте пустым для значения по умолчанию.", "cache_synth_01"] },
  { labels: ["Operator role"], en: ["Declare the requester's role: OPERATOR, RESEARCHER or AUDITOR. Selecting a role does not grant permissions; admission is decided by the Controller.", "OPERATOR"], ru: ["Укажите роль отправителя: OPERATOR, RESEARCHER или AUDITOR. Выбор роли не выдаёт права; допуск определяет Controller.", "OPERATOR"] },
  { labels: ["Subject ID"], en: ["Identify the person or service sending the request. This label is recorded in the intent; it is not an authenticated account.", "operator.alpha"], ru: ["Укажите человека или сервис, отправляющий запрос. Метка записывается в запрос и не является подтверждённой учётной записью.", "operator.alpha"] },
  { labels: ["Timeout (seconds)"], en: ["Request a time budget from 1 to 3600 seconds. The Controller applies its execution policy.", "60"], ru: ["Запросите лимит времени от 1 до 3600 секунд. Controller применяет свою политику выполнения.", "60"] },
  { labels: ["Retry of intent ID (optional)"], en: ["Only for an intentional retry of a known previous intent. Use its actual UUID. If admission is uncertain, check status before submitting again.", "55555555-5555-4555-8555-555555555555 (format only)"], ru: ["Только для намеренного повтора известного запроса. Укажите его реальный UUID. При неизвестном результате допуска сначала проверьте статус.", "55555555-5555-4555-8555-555555555555 (пример формата)"] },
  { labels: ["Request external downloads (Informational intent constraint; controller policy and AdmissionRecord determine actual authority)"], en: ["Declare that the request may need external data downloads. This checkbox grants no network permission. The local synthetic example can leave it unchecked.", "Unchecked for the synthetic 10-gene dataset"], ru: ["Укажите, что запрос может требовать внешней загрузки данных. Флажок не выдаёт разрешение на сеть. Для локального синтетического примера его можно не включать.", "Выключено для синтетического набора с 10 признаками"] },
  { labels: ["Document version"], en: ["Version declared by the controller-register JSON document. It is independent of the application version.", "1.0.0"], ru: ["Версия JSON-документа реестра контроллеров. Она не является версией приложения.", "1.0.0"] },
  { labels: ["Controller ID"], en: ["A unique public identifier for a controller entry in this register. It does not change the live execution destination.", "controller-01"], ru: ["Уникальный открытый идентификатор записи контроллера в реестре. Он не меняет адрес реального выполнения.", "controller-01"] },
  { labels: ["Status"], en: ["The status recorded in this local controller document. Editing this text does not confirm readiness or grant authority.", "UNASSIGNED for an unconfirmed entry"], ru: ["Статус в локальном документе контроллера. Изменение текста не подтверждает готовность и не выдаёт полномочия.", "UNASSIGNED для неподтверждённой записи"] },
  { labels: ["Signer ID"], en: ["Public reference to the expected signer. Enter an identifier, never a private key. A label does not prove key custody.", "signer-01"], ru: ["Открытая ссылка на предполагаемого подписанта. Введите идентификатор, никогда не вводите закрытый ключ. Метка не доказывает владение ключом.", "signer-01"] },
  { labels: ["Identity type"], en: ["Describe the kind of identity supported by your evidence. Leave unknown facts blank.", "organization (if documented)"], ru: ["Опишите тип участника согласно имеющимся подтверждениям. Неизвестные сведения оставьте пустыми.", "organization (если подтверждено)"] },
  { labels: ["Accountable owner ID"], en: ["Public identifier of the responsible owner. Different labels alone do not prove independent owners.", "owner-team-a (if documented)"], ru: ["Открытый идентификатор ответственного владельца. Разные метки сами по себе не доказывают независимость владельцев.", "owner-team-a (если подтверждено)"] },
  { labels: ["Administrative domain ID"], en: ["Identify the actual administration boundary, such as the organization controlling deployment and recovery. Container names do not create independence.", "admin-org-a (if documented)"], ru: ["Укажите реальную границу администрирования: например, организацию, управляющую развёртыванием и восстановлением. Названия контейнеров не создают независимость.", "admin-org-a (если подтверждено)"] },
  { labels: ["Custody boundary ID"], en: ["Public reference to the boundary controlling signing keys and recovery. Use evidence of actual separation; do not enter credentials.", "custody-a (if documented)"], ru: ["Открытая ссылка на границу управления ключами подписи и восстановлением. Укажите подтверждённое разделение; не вводите секреты.", "custody-a (если подтверждено)"] },
  { labels: ["Custody kind"], en: ["Describe how the signing key is held, based on actual evidence. This text does not configure custody.", "hardware-backed (only if verified)"], ru: ["Опишите способ хранения ключа подписи по реальным подтверждениям. Этот текст не настраивает хранение ключей.", "hardware-backed (только если проверено)"] },
  { labels: ["Yes", "No", "Unknown"], en: ["Record an answer to this independence question based on documented facts. Use Unknown when the evidence is missing. A local answer is not an independent attestation.", "Unknown when ownership has not been verified"], ru: ["Ответьте на вопрос о независимости по подтверждённым фактам. При отсутствии доказательств выберите «Неизвестно». Локальный ответ не является независимой аттестацией.", "«Неизвестно», если владелец не проверен"] },
  { labels: ["Evidence references, one per line"], en: ["List references supporting the pairwise review, one per line. The UI stores references; it does not upload or independently verify the referenced evidence.", "evidence/owner-review.json"], ru: ["Укажите ссылки на подтверждения попарной проверки, по одной на строку. Интерфейс сохраняет ссылки, но не загружает и не проверяет доказательства независимо.", "evidence/owner-review.json"] },
  { labels: ["Schema descriptor"], en: ["Choose the schema used to check the document's structure. Structural validity does not establish protocol or governance approval.", "Controller register · 1.0.0"], ru: ["Выберите схему проверки структуры документа. Корректная структура не подтверждает одобрение протокола или полномочий.", "Реестр контроллеров · 1.0.0"] },
  { labels: ["Load Receipt JSON"], en: ["Open an existing execution receipt for inspection. Importing a file does not run a job or turn a local receipt into benchmark qualification.", "receipt-<execution-id>.json"], ru: ["Откройте существующую квитанцию выполнения для просмотра. Импорт файла не запускает задачу и не превращает локальную квитанцию в квалификацию бенчмарка.", "receipt-<execution-id>.json"] },
  { labels: ["Read-only JSON document", "JSON document text"], en: ["The controller-register document behind the form. Read-only views show current values; editing a draft changes only local definitions. Do not include secrets.", "{\"version\":\"1.0.0\",\"controllers\":[]}"], ru: ["Документ реестра контроллеров, лежащий в основе формы. Просмотр показывает текущие значения; редактирование черновика меняет только локальные определения. Не включайте секреты.", "{\"version\":\"1.0.0\",\"controllers\":[]}"] },
];
