-- Generated by formal/scripts/generate_apply_kernel_vectors.py; DO NOT EDIT.
-- Proposal-oracle vectors, not native decoder/admission/refinement evidence.
import DeltaReduce.ApplyKernel
set_option maxRecDepth 16384
set_option maxHeartbeats 8000000
namespace DeltaReduce.ApplyKernelVectors
open ApplyKernel
def lo : Int := -9223372036854775808
def hi : Int := 9223372036854775807
theorem native_0 :
    (deriveApply lo hi [20, -20] [2, -2]
      [⟨⟨1, 1⟩, [1, -1]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([19, -19], [2, -2]) := by decide
theorem native_1 :
    (deriveApply lo hi [20, -20, 20, -20, 20] [2, -2, 2, -2, 2]
      [⟨⟨1, 3⟩, [1, -1, 2, -2, 3]⟩, ⟨⟨1, 3⟩, [0, 1, -1, 2, -2]⟩, ⟨⟨1, 3⟩, [1, -1, 2, -2, 3]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([19, -20, 19, -19, 19], [2, -1, 2, -2, 2]) := by decide
theorem signed_rounding :
    (deriveApply lo hi [20, -20, 0, 1] [1, -1, 1, -1]
      [⟨⟨1, 1⟩, [3, -3, 0, 0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([17, -18, -1, 1], [4, -3, 1, 0]) := by decide
theorem coprime_lcm :
    (deriveApply lo hi [10, -10] [2, -2]
      [⟨⟨1, 2⟩, [3, -3]⟩, ⟨⟨1, 3⟩, [-2, 2]⟩, ⟨⟨1, 6⟩, [7, -7]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([8, -9], [3, -3]) := by decide
theorem zero_weight_domain :
    (deriveApply lo hi [0] [0]
      [⟨⟨0, 1⟩, [9223372036854775807]⟩, ⟨⟨1, 1⟩, [2]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([-2], [2]) := by decide
theorem minimum_survives :
    (deriveApply lo hi [-9223372036854775808] [0]
      [⟨⟨1, 1⟩, [0]⟩] ⟨0, 1⟩ ⟨0, 1⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([-9223372036854775808], [0]) := by decide
theorem maximum_survives :
    (deriveApply lo hi [9223372036854775807] [0]
      [⟨⟨1, 1⟩, [0]⟩] ⟨0, 1⟩ ⟨0, 1⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([9223372036854775807], [0]) := by decide
theorem zero_learning_rate :
    (deriveApply lo hi [10] [2]
      [⟨⟨1, 1⟩, [3]⟩] ⟨0, 1⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([10], [4]) := by decide
theorem nonzero_decay :
    (deriveApply lo hi [20, -20] [2, -2]
      [⟨⟨1, 1⟩, [3, -3]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨1, 2⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([12, -13], [4, -4]) := by decide
theorem nonunit_learning_rate :
    (deriveApply lo hi [20, -20] [0, 0]
      [⟨⟨1, 1⟩, [3, -3]⟩] ⟨2, 3⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      some ([17, -17], [3, -3]) := by decide
theorem not_normalized :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 3⟩, [0]⟩, ⟨⟨1, 3⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem over_normalized :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 1⟩, [0]⟩, ⟨⟨1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem noncanonical_weight :
    (deriveApply lo hi [0] [0]
      [⟨⟨2, 4⟩, [0]⟩, ⟨⟨1, 2⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem negative_weight :
    (deriveApply lo hi [0] [0]
      [⟨⟨-1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem zero_denominator :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 0⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem empty_domains :
    (deriveApply lo hi [0] [0]
      [] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem empty_model :
    (deriveApply lo hi [] []
      [⟨⟨1, 1⟩, []⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem optimizer_shape :
    (deriveApply lo hi [0, 0] [0]
      [⟨⟨1, 1⟩, [0, 0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem domain_shape :
    (deriveApply lo hi [0, 0] [0, 0]
      [⟨⟨1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem zero_weight_bad_value :
    (deriveApply lo hi [0] [0]
      [⟨⟨0, 1⟩, [9223372036854775808]⟩, ⟨⟨1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem lcm_overflow_zero_output :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 3037000499⟩, [0]⟩, ⟨⟨1, 3037000503⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem first_product_overflow_safe_rational :
    (deriveApply lo hi [0] [0]
      [⟨⟨2, 3⟩, [9223372036854775807]⟩, ⟨⟨1, 3⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem second_product_overflow :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 2⟩, [4611686018427387903]⟩, ⟨⟨1, 3⟩, [0]⟩, ⟨⟨1, 6⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem unsafe_prefix_safe_final :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 3⟩, [9223372036854775807]⟩, ⟨⟨1, 3⟩, [9223372036854775807]⟩, ⟨⟨1, 3⟩, [-9223372036854775807]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem momentum_product_overflow :
    (deriveApply lo hi [0] [9223372036854775807]
      [⟨⟨1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨2, 3⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem next_momentum_overflow :
    (deriveApply lo hi [0] [9223372036854775807]
      [⟨⟨1, 1⟩, [1]⟩] ⟨1, 2⟩ ⟨1, 1⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem direction_overflow :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 1⟩, [9223372036854775807]⟩] ⟨1, 2⟩ ⟨1, 1⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem decay_product_overflow :
    (deriveApply lo hi [9223372036854775807] [0]
      [⟨⟨1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨1, 2⟩ ⟨2, 3⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem sum_overflow_before_zero_lr :
    (deriveApply lo hi [9223372036854775807] [0]
      [⟨⟨1, 1⟩, [1]⟩] ⟨0, 1⟩ ⟨0, 1⟩ ⟨1, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem step_product_overflow :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 1⟩, [9223372036854775807]⟩] ⟨2, 3⟩ ⟨0, 1⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem model_subtraction_underflow :
    (deriveApply lo hi [-9223372036854775808] [0]
      [⟨⟨1, 1⟩, [1]⟩] ⟨1, 1⟩ ⟨0, 1⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
theorem invalid_momentum_fraction :
    (deriveApply lo hi [0] [0]
      [⟨⟨1, 1⟩, [0]⟩] ⟨1, 2⟩ ⟨2, 4⟩ ⟨0, 1⟩).map
      (fun result => (result.nextModel, result.nextOptimizer)) =
      none := by decide
end DeltaReduce.ApplyKernelVectors
