import DeltaReduce.PublicVoteEffects
import DeltaReduce.PublicStateVectors
namespace DeltaReduce.PublicVoteEffectsCalculations
open PublicState PublicVoteEffects PublicStateValues PublicStateDocuments PublicStateVectors
set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0
noncomputable def first0 : First state70 state71 value37 := (extractFirst state70 state71 value37).get (by decide +kernel)
theorem extracted0 : extractFirst state70 state71 value37 = some first0 := Option.eq_some_of_isSome _
noncomputable def input0 : Inputs state70 first0.vote := (readInputs state70 first0.vote).get (by decide +kernel)
theorem read0 : readInputs state70 first0.vote = some input0 := Option.eq_some_of_isSome _
theorem insert0_durableVotes : Value.set (insert value192 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))) = value193 := by
  rw [PublicVoteEffects.insertBefore (show value192 ≠ value75 from by decide +kernel) (by rw [encoded_value192,encoded_value75]; exact order_value192_value75)]
  rfl
theorem insert0_parameterVotes : Value.set (insert value194 .nil) = value195 := by
  rfl
theorem rows0 : state71.rows = (expected input0).rows := by
  change state71.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value0),("aggregateRootQCs",value0),("aggregateVotes",value0),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value0),("applyQCs",value0),("applyVotes",value0),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value37 (.integer 5) (.cons value37 value70 (.cons value38 value70 (.cons value39 value70 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value192 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value108),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value0),("parameterResults",value174),("parameterVotes",(.set (insert value194 .nil))),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value91),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value192 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))]
  rw [insert0_durableVotes,insert0_parameterVotes]
  rfl
theorem accepts0 : (check state70 state71 value37).isSome = true := checkFromComputed first0 input0 extracted0 read0 rows0
noncomputable def first1 : First state74 state75 value38 := (extractFirst state74 state75 value38).get (by decide +kernel)
theorem extracted1 : extractFirst state74 state75 value38 = some first1 := Option.eq_some_of_isSome _
noncomputable def input1 : Inputs state74 first1.vote := (readInputs state74 first1.vote).get (by decide +kernel)
theorem read1 : readInputs state74 first1.vote = some input1 := Option.eq_some_of_isSome _
theorem insert1_durableVotes : Value.set (insert value198 (.cons value192 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))) = value199 := by
  rw [PublicVoteEffects.insertAfter (show value198 ≠ value192 from by decide +kernel) (by rw [encoded_value198,encoded_value192]; exact byteLessReverse order_value192_value198)]
  rw [PublicVoteEffects.insertBefore (show value198 ≠ value75 from by decide +kernel) (by rw [encoded_value198,encoded_value75]; exact order_value198_value75)]
  rfl
theorem insert1_parameterVotes : Value.set (insert value200 (.cons value194 .nil)) = value201 := by
  rw [PublicVoteEffects.insertAfter (show value200 ≠ value194 from by decide +kernel) (by rw [encoded_value200,encoded_value194]; exact byteLessReverse order_value194_value200)]
  rfl
theorem rows1 : state75.rows = (expected input1).rows := by
  change state75.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value0),("aggregateRootQCs",value0),("aggregateVotes",value0),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value0),("applyQCs",value0),("applyVotes",value0),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value38 (.integer 5) (.cons value37 value188 (.cons value38 value70 (.cons value39 value70 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value198 (.cons value192 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value196),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value0),("parameterResults",value174),("parameterVotes",(.set (insert value200 (.cons value194 .nil)))),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value193),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value198 (.cons value192 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))]
  rw [insert1_durableVotes,insert1_parameterVotes]
  rfl
theorem accepts1 : (check state74 state75 value38).isSome = true := checkFromComputed first1 input1 extracted1 read1 rows1
noncomputable def first2 : First state78 state79 value39 := (extractFirst state78 state79 value39).get (by decide +kernel)
theorem extracted2 : extractFirst state78 state79 value39 = some first2 := Option.eq_some_of_isSome _
noncomputable def input2 : Inputs state78 first2.vote := (readInputs state78 first2.vote).get (by decide +kernel)
theorem read2 : readInputs state78 first2.vote = some input2 := Option.eq_some_of_isSome _
theorem insert2_durableVotes : Value.set (insert value203 (.cons value192 (.cons value198 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))) = value204 := by
  rw [PublicVoteEffects.insertAfter (show value203 ≠ value192 from by decide +kernel) (by rw [encoded_value203,encoded_value192]; exact byteLessReverse order_value192_value203)]
  rw [PublicVoteEffects.insertAfter (show value203 ≠ value198 from by decide +kernel) (by rw [encoded_value203,encoded_value198]; exact byteLessReverse order_value198_value203)]
  rw [PublicVoteEffects.insertBefore (show value203 ≠ value75 from by decide +kernel) (by rw [encoded_value203,encoded_value75]; exact order_value203_value75)]
  rfl
theorem insert2_parameterVotes : Value.set (insert value205 (.cons value194 (.cons value200 .nil))) = value206 := by
  rw [PublicVoteEffects.insertAfter (show value205 ≠ value194 from by decide +kernel) (by rw [encoded_value205,encoded_value194]; exact byteLessReverse order_value194_value205)]
  rw [PublicVoteEffects.insertAfter (show value205 ≠ value200 from by decide +kernel) (by rw [encoded_value205,encoded_value200]; exact byteLessReverse order_value200_value205)]
  rfl
theorem rows2 : state79.rows = (expected input2).rows := by
  change state79.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value0),("aggregateRootQCs",value0),("aggregateVotes",value0),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value0),("applyQCs",value0),("applyVotes",value0),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value39 (.integer 5) (.cons value37 value188 (.cons value38 value188 (.cons value39 value70 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value203 (.cons value192 (.cons value198 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value131),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value0),("parameterResults",value174),("parameterVotes",(.set (insert value205 (.cons value194 (.cons value200 .nil))))),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value199),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value203 (.cons value192 (.cons value198 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))]
  rw [insert2_durableVotes,insert2_parameterVotes]
  rfl
theorem accepts2 : (check state78 state79 value39).isSome = true := checkFromComputed first2 input2 extracted2 read2 rows2
noncomputable def first3 : First state85 state86 value37 := (extractFirst state85 state86 value37).get (by decide +kernel)
theorem extracted3 : extractFirst state85 state86 value37 = some first3 := Option.eq_some_of_isSome _
noncomputable def input3 : Inputs state85 first3.vote := (readInputs state85 first3.vote).get (by decide +kernel)
theorem read3 : readInputs state85 first3.vote = some input3 := Option.eq_some_of_isSome _
theorem insert3_durableVotes : Value.set (insert value215 (.cons value192 (.cons value198 (.cons value203 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))) = value216 := by
  rw [PublicVoteEffects.insertAfter (show value215 ≠ value192 from by decide +kernel) (by rw [encoded_value215,encoded_value192]; exact byteLessReverse order_value192_value215)]
  rw [PublicVoteEffects.insertAfter (show value215 ≠ value198 from by decide +kernel) (by rw [encoded_value215,encoded_value198]; exact byteLessReverse order_value198_value215)]
  rw [PublicVoteEffects.insertAfter (show value215 ≠ value203 from by decide +kernel) (by rw [encoded_value215,encoded_value203]; exact byteLessReverse order_value203_value215)]
  rw [PublicVoteEffects.insertBefore (show value215 ≠ value75 from by decide +kernel) (by rw [encoded_value215,encoded_value75]; exact order_value215_value75)]
  rfl
theorem insert3_parameterVotes : Value.set (insert value217 (.cons value194 (.cons value200 (.cons value205 .nil)))) = value218 := by
  rw [PublicVoteEffects.insertAfter (show value217 ≠ value194 from by decide +kernel) (by rw [encoded_value217,encoded_value194]; exact byteLessReverse order_value194_value217)]
  rw [PublicVoteEffects.insertAfter (show value217 ≠ value200 from by decide +kernel) (by rw [encoded_value217,encoded_value200]; exact byteLessReverse order_value200_value217)]
  rw [PublicVoteEffects.insertAfter (show value217 ≠ value205 from by decide +kernel) (by rw [encoded_value217,encoded_value205]; exact byteLessReverse order_value205_value217)]
  rfl
theorem rows3 : state86.rows = (expected input3).rows := by
  change state86.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value0),("aggregateRootQCs",value0),("aggregateVotes",value0),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value0),("applyQCs",value0),("applyVotes",value0),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value37 (.integer 6) (.cons value37 value188 (.cons value38 value188 (.cons value39 value188 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value215 (.cons value192 (.cons value198 (.cons value203 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value207),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value209),("parameterResults",value211),("parameterVotes",(.set (insert value217 (.cons value194 (.cons value200 (.cons value205 .nil)))))),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value204),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value215 (.cons value192 (.cons value198 (.cons value203 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))]
  rw [insert3_durableVotes,insert3_parameterVotes]
  rfl
theorem accepts3 : (check state85 state86 value37).isSome = true := checkFromComputed first3 input3 extracted3 read3 rows3
noncomputable def first4 : First state89 state90 value38 := (extractFirst state89 state90 value38).get (by decide +kernel)
theorem extracted4 : extractFirst state89 state90 value38 = some first4 := Option.eq_some_of_isSome _
noncomputable def input4 : Inputs state89 first4.vote := (readInputs state89 first4.vote).get (by decide +kernel)
theorem read4 : readInputs state89 first4.vote = some input4 := Option.eq_some_of_isSome _
theorem insert4_durableVotes : Value.set (insert value221 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))) = value222 := by
  rw [PublicVoteEffects.insertAfter (show value221 ≠ value192 from by decide +kernel) (by rw [encoded_value221,encoded_value192]; exact byteLessReverse order_value192_value221)]
  rw [PublicVoteEffects.insertAfter (show value221 ≠ value198 from by decide +kernel) (by rw [encoded_value221,encoded_value198]; exact byteLessReverse order_value198_value221)]
  rw [PublicVoteEffects.insertAfter (show value221 ≠ value203 from by decide +kernel) (by rw [encoded_value221,encoded_value203]; exact byteLessReverse order_value203_value221)]
  rw [PublicVoteEffects.insertAfter (show value221 ≠ value215 from by decide +kernel) (by rw [encoded_value221,encoded_value215]; exact byteLessReverse order_value215_value221)]
  rw [PublicVoteEffects.insertBefore (show value221 ≠ value75 from by decide +kernel) (by rw [encoded_value221,encoded_value75]; exact order_value221_value75)]
  rfl
theorem insert4_parameterVotes : Value.set (insert value223 (.cons value194 (.cons value200 (.cons value205 (.cons value217 .nil))))) = value224 := by
  rw [PublicVoteEffects.insertAfter (show value223 ≠ value194 from by decide +kernel) (by rw [encoded_value223,encoded_value194]; exact byteLessReverse order_value194_value223)]
  rw [PublicVoteEffects.insertAfter (show value223 ≠ value200 from by decide +kernel) (by rw [encoded_value223,encoded_value200]; exact byteLessReverse order_value200_value223)]
  rw [PublicVoteEffects.insertAfter (show value223 ≠ value205 from by decide +kernel) (by rw [encoded_value223,encoded_value205]; exact byteLessReverse order_value205_value223)]
  rw [PublicVoteEffects.insertAfter (show value223 ≠ value217 from by decide +kernel) (by rw [encoded_value223,encoded_value217]; exact byteLessReverse order_value217_value223)]
  rfl
theorem rows4 : state90.rows = (expected input4).rows := by
  change state90.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value0),("aggregateRootQCs",value0),("aggregateVotes",value0),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value0),("applyQCs",value0),("applyVotes",value0),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value38 (.integer 6) (.cons value37 value212 (.cons value38 value188 (.cons value39 value188 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value221 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value219),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value209),("parameterResults",value211),("parameterVotes",(.set (insert value223 (.cons value194 (.cons value200 (.cons value205 (.cons value217 .nil))))))),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value216),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value221 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))]
  rw [insert4_durableVotes,insert4_parameterVotes]
  rfl
theorem accepts4 : (check state89 state90 value38).isSome = true := checkFromComputed first4 input4 extracted4 read4 rows4
noncomputable def first5 : First state93 state94 value39 := (extractFirst state93 state94 value39).get (by decide +kernel)
theorem extracted5 : extractFirst state93 state94 value39 = some first5 := Option.eq_some_of_isSome _
noncomputable def input5 : Inputs state93 first5.vote := (readInputs state93 first5.vote).get (by decide +kernel)
theorem read5 : readInputs state93 first5.vote = some input5 := Option.eq_some_of_isSome _
theorem insert5_durableVotes : Value.set (insert value227 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))) = value228 := by
  rw [PublicVoteEffects.insertAfter (show value227 ≠ value192 from by decide +kernel) (by rw [encoded_value227,encoded_value192]; exact byteLessReverse order_value192_value227)]
  rw [PublicVoteEffects.insertAfter (show value227 ≠ value198 from by decide +kernel) (by rw [encoded_value227,encoded_value198]; exact byteLessReverse order_value198_value227)]
  rw [PublicVoteEffects.insertAfter (show value227 ≠ value203 from by decide +kernel) (by rw [encoded_value227,encoded_value203]; exact byteLessReverse order_value203_value227)]
  rw [PublicVoteEffects.insertAfter (show value227 ≠ value215 from by decide +kernel) (by rw [encoded_value227,encoded_value215]; exact byteLessReverse order_value215_value227)]
  rw [PublicVoteEffects.insertAfter (show value227 ≠ value221 from by decide +kernel) (by rw [encoded_value227,encoded_value221]; exact byteLessReverse order_value221_value227)]
  rw [PublicVoteEffects.insertBefore (show value227 ≠ value75 from by decide +kernel) (by rw [encoded_value227,encoded_value75]; exact order_value227_value75)]
  rfl
theorem insert5_parameterVotes : Value.set (insert value229 (.cons value194 (.cons value200 (.cons value205 (.cons value217 (.cons value223 .nil)))))) = value230 := by
  rw [PublicVoteEffects.insertAfter (show value229 ≠ value194 from by decide +kernel) (by rw [encoded_value229,encoded_value194]; exact byteLessReverse order_value194_value229)]
  rw [PublicVoteEffects.insertAfter (show value229 ≠ value200 from by decide +kernel) (by rw [encoded_value229,encoded_value200]; exact byteLessReverse order_value200_value229)]
  rw [PublicVoteEffects.insertAfter (show value229 ≠ value205 from by decide +kernel) (by rw [encoded_value229,encoded_value205]; exact byteLessReverse order_value205_value229)]
  rw [PublicVoteEffects.insertAfter (show value229 ≠ value217 from by decide +kernel) (by rw [encoded_value229,encoded_value217]; exact byteLessReverse order_value217_value229)]
  rw [PublicVoteEffects.insertAfter (show value229 ≠ value223 from by decide +kernel) (by rw [encoded_value229,encoded_value223]; exact byteLessReverse order_value223_value229)]
  rfl
theorem rows5 : state94.rows = (expected input5).rows := by
  change state94.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value0),("aggregateRootQCs",value0),("aggregateVotes",value0),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value0),("applyQCs",value0),("applyVotes",value0),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value39 (.integer 6) (.cons value37 value212 (.cons value38 value212 (.cons value39 value188 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value227 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value225),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value209),("parameterResults",value211),("parameterVotes",(.set (insert value229 (.cons value194 (.cons value200 (.cons value205 (.cons value217 (.cons value223 .nil)))))))),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value222),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value227 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))))]
  rw [insert5_durableVotes,insert5_parameterVotes]
  rfl
theorem accepts5 : (check state93 state94 value39).isSome = true := checkFromComputed first5 input5 extracted5 read5 rows5
noncomputable def first6 : First state116 state117 value37 := (extractFirst state116 state117 value37).get (by decide +kernel)
theorem extracted6 : extractFirst state116 state117 value37 = some first6 := Option.eq_some_of_isSome _
noncomputable def input6 : Inputs state116 first6.vote := (readInputs state116 first6.vote).get (by decide +kernel)
theorem read6 : readInputs state116 first6.vote = some input6 := Option.eq_some_of_isSome _
theorem insert6_durableVotes : Value.set (insert value265 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))))) = value266 := by
  rw [PublicVoteEffects.insertBefore (show value265 ≠ value192 from by decide +kernel) (by rw [encoded_value265,encoded_value192]; exact order_value265_value192)]
  rfl
theorem insert6_applyVotes : Value.set (insert value260 .nil) = value261 := by
  rfl
theorem rows6 : state117.rows = (expected input6).rows := by
  change state117.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value233),("aggregateRootQCs",value235),("aggregateVotes",value239),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value249),("applyQCs",value0),("applyVotes",(.set (insert value260 .nil))),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value37 (.integer 8) (.cons value37 value250 (.cons value38 value250 (.cons value39 value250 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value265 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value257),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value259),("parameterResults",value211),("parameterVotes",value230),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value256),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value265 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))))))))]
  rw [insert6_durableVotes,insert6_applyVotes]
  rfl
theorem accepts6 : (check state116 state117 value37).isSome = true := checkFromComputed first6 input6 extracted6 read6 rows6
noncomputable def first7 : First state120 state121 value38 := (extractFirst state120 state121 value38).get (by decide +kernel)
theorem extracted7 : extractFirst state120 state121 value38 = some first7 := Option.eq_some_of_isSome _
noncomputable def input7 : Inputs state120 first7.vote := (readInputs state120 first7.vote).get (by decide +kernel)
theorem read7 : readInputs state120 first7.vote = some input7 := Option.eq_some_of_isSome _
theorem insert7_durableVotes : Value.set (insert value271 (.cons value265 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))))))) = value272 := by
  rw [PublicVoteEffects.insertAfter (show value271 ≠ value265 from by decide +kernel) (by rw [encoded_value271,encoded_value265]; exact byteLessReverse order_value265_value271)]
  rw [PublicVoteEffects.insertBefore (show value271 ≠ value192 from by decide +kernel) (by rw [encoded_value271,encoded_value192]; exact order_value271_value192)]
  rfl
theorem insert7_applyVotes : Value.set (insert value268 (.cons value260 .nil)) = value269 := by
  rw [PublicVoteEffects.insertAfter (show value268 ≠ value260 from by decide +kernel) (by rw [encoded_value268,encoded_value260]; exact byteLessReverse order_value260_value268)]
  rfl
theorem rows7 : state121.rows = (expected input7).rows := by
  change state121.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value233),("aggregateRootQCs",value235),("aggregateVotes",value239),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value249),("applyQCs",value0),("applyVotes",(.set (insert value268 (.cons value260 .nil)))),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value38 (.integer 8) (.cons value37 value262 (.cons value38 value250 (.cons value39 value250 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value271 (.cons value265 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value267),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value259),("parameterResults",value211),("parameterVotes",value230),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value266),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value271 (.cons value265 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))))))))]
  rw [insert7_durableVotes,insert7_applyVotes]
  rfl
theorem accepts7 : (check state120 state121 value38).isSome = true := checkFromComputed first7 input7 extracted7 read7 rows7
noncomputable def first8 : First state124 state125 value39 := (extractFirst state124 state125 value39).get (by decide +kernel)
theorem extracted8 : extractFirst state124 state125 value39 = some first8 := Option.eq_some_of_isSome _
noncomputable def input8 : Inputs state124 first8.vote := (readInputs state124 first8.vote).get (by decide +kernel)
theorem read8 : readInputs state124 first8.vote = some input8 := Option.eq_some_of_isSome _
theorem insert8_durableVotes : Value.set (insert value277 (.cons value265 (.cons value271 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))))))) = value278 := by
  rw [PublicVoteEffects.insertAfter (show value277 ≠ value265 from by decide +kernel) (by rw [encoded_value277,encoded_value265]; exact byteLessReverse order_value265_value277)]
  rw [PublicVoteEffects.insertAfter (show value277 ≠ value271 from by decide +kernel) (by rw [encoded_value277,encoded_value271]; exact byteLessReverse order_value271_value277)]
  rw [PublicVoteEffects.insertBefore (show value277 ≠ value192 from by decide +kernel) (by rw [encoded_value277,encoded_value192]; exact order_value277_value192)]
  rfl
theorem insert8_applyVotes : Value.set (insert value274 (.cons value260 (.cons value268 .nil))) = value275 := by
  rw [PublicVoteEffects.insertAfter (show value274 ≠ value260 from by decide +kernel) (by rw [encoded_value274,encoded_value260]; exact byteLessReverse order_value260_value274)]
  rw [PublicVoteEffects.insertAfter (show value274 ≠ value268 from by decide +kernel) (by rw [encoded_value274,encoded_value268]; exact byteLessReverse order_value268_value274)]
  rfl
theorem rows8 : state125.rows = (expected input8).rows := by
  change state125.rows = [("abortQCs",value0),("abortReason",value1),("abortRequests",value0),("abortVotes",value0),("aggregateCandidates",value233),("aggregateRootQCs",value235),("aggregateVotes",value239),("aggregationPlanCertificates",value42),("alive",value44),("apcVotes",value49),("applyCandidates",value249),("applyQCs",value0),("applyVotes",(.set (insert value274 (.cons value260 (.cons value268 .nil))))),("availabilityAttestations",value57),("availabilityCertificates",value13),("availabilityShortfalls",value0),("availableArtifacts",value60),("availableTickets",value27),("byzantine",value61),("certificateRejections",value0),("certificateReplayReceipts",value0),("closedInputBodies",value62),("commitments",value68),("corruptArtifacts",value0),("crashCoverage",value0),("currentAdvanceReceipts",value0),("currentCheckpoint",value69),("currentReplayReceipts",value0),("durableSequence",(.function (update value39 (.integer 8) (.cons value37 value262 (.cons value38 value262 (.cons value39 value250 (.cons value43 value64 .nil))))))),("durableVotes",(.set (insert value277 (.cons value265 (.cons value271 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil)))))))))))))))))))))))))),("ecVotes",value95),("eligibilityCertificates",value97),("finalizedCertificates",value99),("inputSetCertificates",value101),("iscVotes",value105),("lateAvailabilityEvidence",value0),("leaseActive",value0),("leaseEpoch",value106),("leaseOwner",value107),("logicalTime",value273),("materializedArtifacts",value60),("messageMultiplicity",value0),("messages",value0),("parameterQCs",value259),("parameterResults",value211),("parameterVotes",value230),("partition",value0),("pendingPointerRecoveries",value0),("phase",value175),("proposals",value177),("publishedObjects",value0),("receivedVotes",value272),("recoveryState",value179),("reduceApplyRejections",value0),("rejectedCommitments",value0),("rejectedPublications",value0),("repairAttempts",value180),("seedTranscripts",value181),("ticketPlan",value187),("timeoutObservations",value0),("timeoutVotes",value0),("view",value64),("viewChangeQCs",value0),("volatileVotes",(.set (insert value277 (.cons value265 (.cons value271 (.cons value192 (.cons value198 (.cons value203 (.cons value215 (.cons value221 (.cons value227 (.cons value253 (.cons value254 (.cons value255 (.cons value75 (.cons value76 (.cons value77 (.cons value79 (.cons value80 (.cons value81 (.cons value83 (.cons value84 (.cons value85 (.cons value88 (.cons value89 (.cons value90 .nil))))))))))))))))))))))))))]
  rw [insert8_durableVotes,insert8_applyVotes]
  rfl
theorem accepts8 : (check state124 state125 value39).isSome = true := checkFromComputed first8 input8 extracted8 read8 rows8
end DeltaReduce.PublicVoteEffectsCalculations
