import image1 from "./images/slide-1.png";
import image2 from "./images/slide-2.png";
import image3 from "./images/slide-3.png";
import image4 from "./images/slide-4.png";
import image5 from "./images/slide-5.png";
import image6 from "./images/slide-6.png";
import image7 from "./images/slide-7.png";

export const slides = [
  { image: image1,
    en: { title: "The big picture", summary: "Workers train locally. Validators first agree on the exact inputs, compute a deterministic aggregate, then separately approve its application to the next checkpoint.", note: "The drawing is an overview. The full protocol also binds eligibility, aggregation plans, arithmetic profiles and certificate parents. It is not a live execution trace." },
    ru: { title: "Общая идея", summary: "Воркеры обучаются локально. Валидаторы сначала согласуют точные входы, вычисляют детерминированный агрегат и отдельно подтверждают его применение к следующей контрольной точке.", note: "Рисунок показывает общую схему. Полный протокол также связывает допустимость входов, планы агрегации, профили арифметики и родительские сертификаты. Это не журнал выполнения." } },
  { image: image2,
    en: { title: "Who does what", summary: "A worker produces an update. Its content identity and ticket metadata connect it to the round. Validators freeze one agreed input set in the InputSetCertificate (ISC).", note: "A content hash alone does not prove availability or round membership. The accepted protocol binds tickets, commitments and availability certificates. Decimal weights and ‘2/3’ in the illustration are shorthand, not canonical field encodings or the exact integer quorum rule." },
    ru: { title: "Кто за что отвечает", summary: "Воркер создаёт обновление. Идентификатор содержимого и метаданные заявки связывают его с раундом. Валидаторы фиксируют согласованный набор входов в InputSetCertificate (ISC).", note: "Один хеш содержимого не доказывает доступность или принадлежность к раунду. Протокол связывает заявки, commitments и сертификаты доступности. Дробные веса и «2/3» на рисунке — условные обозначения, а не канонические поля или точное правило целочисленного кворума." } },
  { image: image3,
    en: { title: "Tickets, parents and round rules", summary: "A ticket references the update; the parent identifies the starting checkpoint; RoundConfig fixes the round’s rules. ISC freezes the exact accepted input set.", note: "Sharing a parent is necessary but does not by itself make tickets valid for one round. The full round/configuration/epoch context, schema, arithmetic profile and required certificates must also match." },
    ru: { title: "Заявки, родительская модель и правила раунда", summary: "Заявка ссылается на обновление, parent задаёт исходную контрольную точку, а RoundConfig фиксирует правила раунда. ISC закрепляет точный принятый набор входов.", note: "Одинаковый parent необходим, но сам по себе не делает заявки допустимыми в одном раунде. Должны совпадать полный контекст раунда, конфигурации и эпохи, схема, профиль арифметики и требуемые сертификаты." } },
  { image: image4,
    en: { title: "Why a quorum needs 2f + 1 votes", summary: "With 3f + 1 validators and at most f faulty participants, a quorum requires 2f + 1 votes. For f = 1, three out of four validators must agree.", note: "Safety relies on authenticated, context-bound votes and durable prevention of conflicting votes. Quorum intersection does not guarantee progress if too few honest participants are reachable." },
    ru: { title: "Почему кворуму нужны 2f + 1 голосов", summary: "При 3f + 1 валидаторах и не более f неисправных участниках кворум требует 2f + 1 голосов. При f = 1 должны согласиться трое из четырёх.", note: "Безопасность опирается на аутентифицированные голоса с точным контекстом и устойчивый запрет конфликтующих голосов. Пересечение кворумов не гарантирует прогресс при нехватке доступных честных участников." } },
  { image: image5,
    en: { title: "From shards to a single result", summary: "The same frozen inputs, domain-pure assignment and exact arithmetic let honest validators reproduce the same result. Partial results must retain their weights and certificate lineage.", note: "The original image contains three arithmetic errors. Correct values: shard 1 = 130/6 = 65/3 ≈ 21.667; shard 2 = 50/4 = 12.5; shard 3 = 76/6 = 38/3 ≈ 12.667. These are explanatory weighted means, not consensus floating-point operations. The hash(ticket_id) % 3 formula is illustrative, not the canonical domain/shard assignment algorithm.", correction: true },
    ru: { title: "От шардов к единому результату", summary: "Одинаковые зафиксированные входы, разбиение без смешивания доменов и точная арифметика позволяют честным валидаторам воспроизвести один результат. Частичные результаты сохраняют веса и цепочку сертификатов.", note: "В исходном рисунке три арифметические ошибки. Верно: шард 1 = 130/6 = 65/3 ≈ 21,667; шард 2 = 50/4 = 12,5; шард 3 = 76/6 = 38/3 ≈ 12,667. Это поясняющие взвешенные средние, а не вычисления с плавающей точкой в консенсусе. Формула hash(ticket_id) % 3 условна и не задаёт канонический алгоритм назначения доменов и шардов.", correction: true } },
  { image: image6,
    en: { title: "The overlap that protects agreement", summary: "Two quorums of size 2f + 1 drawn from 3f + 1 validators overlap in at least f + 1 participants. At least one participant in that intersection is honest.", note: "Under the stated fault bound and the same formal uniqueness context, durable no-double-vote rules prevent two conflicting certified decisions. This is a safety argument, not evidence of training quality." },
    ru: { title: "Пересечение, которое защищает согласие", summary: "Два кворума по 2f + 1 голосов из 3f + 1 валидаторов пересекаются минимум по f + 1 участникам. Хотя бы один участник в пересечении честный.", note: "При заданной границе неисправностей и одинаковом формальном контексте уникальности устойчивый запрет двойного голосования исключает два конфликтующих сертифицированных решения. Это аргумент безопасности, а не доказательство качества обучения." } },
  { image: image7,
    en: { title: "Assign shards without mixing domains", summary: "In this five-shard example, give both active domains one shard first. Allocate the remaining three by ticket proportions and largest remainders: domain A gets three shards in total, domain B gets two.", note: "A has 8 tickets and B has 2: ideal remaining shares are 2.4 and 0.6. The floors allocate two to A; the last goes to B. The illustration assumes enough shards for all active domains. Actual ordering, tie-breaking and arithmetic are fixed by the accepted protocol, not chosen by this viewer." },
    ru: { title: "Распределение шардов без смешивания доменов", summary: "В примере с пятью шардами сначала выделяем каждому из двух активных доменов по одному. Оставшиеся три распределяем по числу заявок методом наибольших остатков: всего три шарда у домена A и два у B.", note: "У A восемь заявок, у B две: идеальные доли оставшихся шардов равны 2,4 и 0,6. Целые части дают два шарда A, последний получает B. Пример предполагает достаточное число шардов для всех активных доменов. Порядок, разрешение равенств и арифметику задаёт принятый протокол, а не этот просмотрщик." } },
] as const;

export function slideFromSearch(search: string): number {
  const value = new URLSearchParams(search).get("slide");
  return value && /^[1-7]$/.test(value) ? Number(value) - 1 : 0;
}
